[
  {
    code: 1,
    link: null,
    name: "Accuracy+16",
    type: "NORMAL",
    view: `Accuracy +16`,
  },
  {
    code: 2,
    link: null,
    name: "Dodge+16",
    type: "NORMAL",
    view: `Dodge +16`,
  },
  {
    code: 3,
    link: null,
    name: "ASPD+140",
    type: "NORMAL",
    view: `ASPD +140`,
  },
  {
    code: 4,
    link: null,
    name: "CSPD+140",
    type: "NORMAL",
    view: `CSPD +140`,
  },
  {
    code: 5,
    link: null,
    name: "DEX+7",
    type: "NORMAL",
    view: `DEX +7`,
  },
  {
    code: 6,
    link: null,
    name: "INT+7",
    type: "NORMAL",
    view: `INT +7`,
  },
  {
    code: 7,
    link: null,
    name: "STR+7",
    type: "NORMAL",
    view: `STR +7`,
  },
  {
    code: 8,
    link: null,
    name: "AGI+7",
    type: "NORMAL",
    view: `AGI +7`,
  },
  {
    code: 9,
    link: null,
    name: "Rampion",
    type: "NORMAL",
    view: `Critical Rate +10%\nStability +2%\nShort Range Damage -1%`,
  },
  {
    code: 10,
    link: null,
    name: "Accuracy+14",
    type: "NORMAL",
    view: `Accuracy +14`,
  },
  {
    code: 12,
    link: null,
    name: "Dodge+14",
    type: "NORMAL",
    view: `Dodge +14`,
  },
  {
    code: 13,
    link: null,
    name: "VIT+14",
    type: "NORMAL",
    view: `VIT +14`,
  },
  {
    code: 14,
    link: null,
    name: "Gigantic Octopus",
    type: "NORMAL",
    view: `Attack MP Recovery +5\nCritical Rate +10\nASPD +150\nCSPD +250\nFire resistance -4%\nAilment Resistance -2%\nReduksi DMG (Bowling) -1%`,
  },
  {
    code: 15,
    link: null,
    name: "HP+700",
    type: "NORMAL",
    view: `HP +700`,
  },
  {
    code: 16,
    link: null,
    name: "CSPD+120",
    type: "NORMAL",
    view: `CSPD +120`,
  },
  {
    code: 17,
    link: null,
    name: "INT+6",
    type: "NORMAL",
    view: `INT +6`,
  },
  {
    code: 18,
    link: null,
    name: "MP+300",
    type: "NORMAL",
    view: `CSPD +120`,
  },
  {
    code: 19,
    link: null,
    name: "STR+6",
    type: "NORMAL",
    view: `STR +6`,
  },
  {
    code: 20,
    link: null,
    name: "AGI+6",
    type: "NORMAL",
    view: `AGI +6`,
  },
  {
    code: 21,
    link: null,
    name: "VIT+6",
    type: "NORMAL",
    view: `VIT +6`,
  },
  {
    code: 22,
    link: null,
    name: "Gravicep",
    type: "NORMAL",
    view: `Short Range Damage +7%\nAccuracy +3%\nMaxMP +200\nCritical Rate -5\nMaxHP -100`,
  },
  {
    code: 23,
    link: null,
    name: "DODGE+12",
    type: "NORMAL",
    view: `DODGE +12`,
  },
  {
    code: 24,
    link: null,
    name: "ASPD+120",
    type: "NORMAL",
    view: `ASPD +120`,
  },
  {
    code: 25,
    link: null,
    name: "Shawle",
    type: "NORMAL",
    view: `Anticipate 5%\nGuard Break 5%\nAccuracy +20%\nAggro +10%`,
  },
  {
    code: 26,
    link: null,
    name: "Gerumi",
    type: "NORMAL",
    view: `MaxHP +200\nMaxMP +100`,
  },
  {
    code: 27,
    link: null,
    name: "DEX+6",
    type: "NORMAL",
    view: `DEX +6`,
  },
  {
    code: 28,
    link: null,
    name: "Accuracy+12",
    type: "NORMAL",
    view: `Accuracy +12`,
  },
  {
    code: 29,
    link: null,
    name: "Critical Rate+5",
    type: "NORMAL",
    view: `Critical Rate +5`,
  },
  {
    code: 30,
    link: null,
    name: "STR+5",
    type: "NORMAL",
    view: `STR+5`,
  },
  {
    code: 31,
    link: null,
    name: "Carbuncle",
    type: "NORMAL",
    view: `MaxHP +1000\nReflect +10%\nDodge -10%`,
  },
  {
    code: 32,
    link: null,
    name: "VIT+5",
    type: "NORMAL",
    view: `VIT +5`,
  },
  {
    code: 33,
    link: null,
    name: "Mithurna Lynx",
    type: "NORMAL",
    view: `Short Range Damage +3%\nStability +3%\nEvasion Recharge +3%\nLong Range Damage -9%`,
  },
  {
    code: 34,
    link: null,
    name: "HP+500",
    type: "NORMAL",
    view: `HP +500`,
  },
  {
    code: 35,
    link: null,
    name: "Yashiro Azuki",
    type: "NORMAL",
    view: `EXP +1%\nMaxHP +200\nMaxMP +100`,
  },
  {
    code: 36,
    link: null,
    name: "P. Avatar",
    type: "NORMAL",
    view: `Untradable
    EXP +1%\nFire resistance +1%\nWind resistance +%\nWater resistance +1%\nEarth resistance +1%\nLight resistance +1%\nDark resistance -1%`,
  },
  {
    code: 37,
    link: null,
    name: "Fanadon",
    type: "NORMAL",
    view: `Critical Damage +3\nReduksi DMG (Sekitar Pemain) -3%\nReduksi DMG (Sekitar Musuh) -3%`,
  },
  {
    code: 38,
    link: null,
    name: "INT+5",
    type: "NORMAL",
    view: `INT +5`,
  },
  {
    code: 39,
    link: null,
    name: "DEX+5",
    type: "NORMAL",
    view: `DEX +5`,
  },
  {
    code: 40,
    link: null,
    name: "INT+4",
    type: "NORMAL",
    view: `INT +4`,
  },
  {
    code: 41,
    link: null,
    name: "Critical Rate+4",
    type: "NORMAL",
    view: `Critical Rate +4`,
  },
  {
    code: 42,
    link: null,
    name: "DEX+4",
    type: "NORMAL",
    view: `DEX +4`,
  },
  {
    code: 43,
    link: null,
    name: "Dodge+8",
    type: "NORMAL",
    view: `Dodge +8`,
  },
  {
    code: 44,
    link: null,
    type: "NORMAL",
    name: "Accuracy+10",
    view: `Accuracy +10`,
  },
  {
    code: 45,
    link: null,
    type: "NORMAL",
    name: "ASPD+100",
    view: `ASPD +100`,
  },
  {
    code: 46,
    link: null,
    type: "NORMAL",
    name: "CSPD+100",
    view: `CSPD +100`,
  },
  {
    code: 47,
    link: null,
    type: "NORMAL",
    name: "Dodge+10",
    view: `Dodge +10`,
  },
  {
    code: 48,
    link: null,
    type: "NORMAL",
    name: "",
    view: ``,
  },
  {
    code: 49,
    link: null,
    type: "NORMAL",
    name: "AGI+5",
    view: `AGI +5`,
  },
  {
    code: 50,
    link: null,
    type: "NORMAL",
    name: "Odelon Machina",
    view: `Dodge -5%\nEvasion Recharge -5%\nUnsheathe Attack +10%`,
  },
  {
    code: 51,
    link: null,
    type: "NORMAL",
    name: "Gigant Knight",
    view: `ATK +1%\nCritical Damage +1\nSTR +1%\nAccuracy -10%\nCritical Rate -10%`,
  },
  {
    code: 52,
    link: null,
    type: "NORMAL",
    name: "VIT+4",
    view: `VIT +4`,
  },
  {
    code: 53,
    link: null,
    type: "NORMAL",
    name: "VIT+3",
    view: `VIT +3`,
  },
  {
    code: 54,
    link: null,
    type: "NORMAL",
    name: "",
    view: ``,
  },
  {
    code: 55,
    link: null,
    type: "NORMAL",
    name: "VIT+2",
    view: `VIT +2`,
  },
  {
    code: 56,
    link: null,
    type: "NORMAL",
    name: "HP+600",
    view: `MaxHP +600`,
  },
  {
    code: 57,
    link: null,
    type: "NORMAL",
    name: "Super Night Mushroom",
    view: `MaxHP +500\nLong Range Damage +1%\nShort Range Damage +1%`,
  },
  {
    code: 58,
    link: null,
    type: "NORMAL",
    name: "STR+4",
    view: `STR +4`,
  },
  {
    code: 59,
    link: null,
    type: "NORMAL",
    name: "STR+3",
    view: `STR +3`,
  },
  {
    code: 60,
    link: null,
    type: "NORMAL",
    name: "",
    view: ``,
  },
  {
    code: 61,
    link: null,
    type: "NORMAL",
    name: "STR+2",
    view: `STR +2`,
  },
  {
    code: 62,
    link: null,
    type: "NORMAL",
    name: "STR+1",
    view: `STR +1`,
  },
  {
    code: 63,
    link: null,
    type: "NORMAL",
    name: "Silver Roar",
    view: `MaxHP -8%\nAttack MP Recovery +4`,
  },
  {
    code: 64,
    link: null,
    type: "NORMAL",
    name: "Scrader",
    view: `Natural MP Regen -10%\nMaxHP +300\nMATK +3%\nPhysical Resistance -20%\nLong Range Damage +2%`,
  },
  {
    code: 65,
    link: null,
    type: "NORMAL",
    name: "Ruin Golem",
    view: `MaxHP +200\nMDEF +5%\nMagical Resistance +1%`,
  },
  {
    code: 66,
    link: null,
    type: "NORMAL",
    name: "",
    view: ``,
  },
  {
    code: 67,
    link: null,
    type: "NORMAL",
    name: "Nurethoth",
    view: `ATK +3%\nMATK +3%\nASPD -150\nCSPD -150`,
  },
  {
    code: 68,
    link: null,
    type: "NORMAL",
    name: "MP+50",
    view: `MaxMP +50`,
  },
  {
    code: 69,
    link: null,
    type: "NORMAL",
    name: "MP+200",
    view: `MaxMP +200`,
  },
  {
    code: 70,
    link: null,
    type: "NORMAL",
    name: "MP+150",
    view: `MaxMP +150`,
  },
  {
    code: 71,
    link: null,
    type: "NORMAL",
    name: "MP+100",
    view: `MaxMP +100`,
  },
  {
    code: 72,
    link: null,
    type: "NORMAL",
    name: "",
    view: ``,
  },
  {
    code: 73,
    link: null,
    type: "NORMAL",
    name: "Mochelo",
    view: `MaxHP +5%\nCSPD +10%`,
  },
  {
    code: 74,
    link: null,
    type: "NORMAL",
    name: "Minotaur",
    view: `ASPD +10%\nMaxHP +5%`,
  },
  {
    code: 75,
    link: null,
    type: "NORMAL",
    name: "Metal Stinger",
    view: `ATK +2%\nMagical Resistance-10%\nCritical Damage +3\nMotion Speed -1%`,
  },
  {
    code: 76,
    link: null,
    type: "NORMAL",
    name: "Megiston",
    view: `STR +1\nINT +1\nVIT +1\nAGI +1\nDEX +1\nMaxHP +100\nMaxMP +50`,
  },
  {
    code: 77,
    link: null,
    type: "NORMAL",
    name: "Mauez",
    view: `MaxMP +150\nAccuracy -4%\nCritical Rate +2`,
  },
  {
    code: 78,
    link: null,
    type: "NORMAL",
    name: "",
    view: ``,
  },
  {
    code: 79,
    link: null,
    type: "NORMAL",
    name: "Masked Warrior",
    view: `MaxHP -3%\nAccuracy -3\nATK +1%\nMATK +1%\nAttack MP Recovery +2`,
  },
  {
    code: 80,
    link: null,
    type: "NORMAL",
    name: "King Potum",
    view: `MaxHP +10%\nPhysical Resistance -5%\nMagical Resistance -5%`,
  },
  {
    code: 81,
    link: null,
    type: "NORMAL",
    name: "Inzanio",
    view: `Guard Recharge +1%\nAttack MP Recovery -1\nWeapon ATK +10\nFractional Barrier+3%`,
  },
  {
    code: 82,
    link: null,
    type: "NORMAL",
    name: "INT+3",
    view: `INT +3`,
  },
  {
    code: 83,
    link: null,
    type: "NORMAL",
    name: "INT+2",
    view: `INT +2`,
  },
  {
    code: 84,
    link: null,
    type: "NORMAL",
    name: "",
    view: ``,
  },
  {
    code: 85,
    link: null,
    type: "NORMAL",
    name: "INT+1",
    view: `INT +1`,
  },
  {
    code: 86,
    link: null,
    type: "NORMAL",
    name: "HP+400",
    view: `MaxHP +400`,
  },
  {
    code: 87,
    link: null,
    type: "NORMAL",
    name: "HP+300",
    view: `MaxHP +300`,
  },
  {
    code: 88,
    link: null,
    type: "NORMAL",
    name: "HP+200",
    view: `MaxHP +200`,
  },
  {
    code: 89,
    link: null,
    type: "NORMAL",
    name: "HP+100",
    view: `MaxHP +100`,
  },
  {
    code: 90,
    link: null,
    type: "NORMAL",
    name: "",
    view: ``,
  },
  {
    code: 91,
    link: null,
    type: "NORMAL",
    name: "Gespenst",
    view: `MaxMP +150\nATK -1%\nMATK -1%`,
  },
  {
    code: 92,
    link: null,
    type: "NORMAL",
    name: "Forest Wolf",
    view: `Dodge +6\nEvasion Recharge +2%`,
  },
  {
    code: 93,
    link: null,
    type: "NORMAL",
    name: "Flare Volg",
    view: `STR +3\nMagical Resistance -4%\nLong Range Damage +2%`,
  },
  {
    code: 94,
    link: null,
    type: "NORMAL",
    name: "Dodge+6",
    view: `Dodge +6`,
  },
  {
    code: 95,
    link: null,
    type: "NORMAL",
    name: "Dodge+4",
    view: `Dodge +4`,
  },
  {
    code: 96,
    link: null,
    type: "NORMAL",
    name: "",
    view: ``,
  },
  {
    code: 97,
    link: null,
    type: "NORMAL",
    name: "Dodge+2",
    view: `Dodge +2`,
  },
  {
    code: 98,
    link: null,
    type: "NORMAL",
    name: "DEX+3",
    view: `DEX +3`,
  },
  {
    code: 99,
    link: null,
    type: "NORMAL",
    name: "DEX+2",
    view: `DEX +2`,
  },
  {
    code: 100,
    link: null,
    type: "NORMAL",
    name: "DEX+1",
    view: `DEX +1`,
  },
  {
    code: 101,
    link: null,
    type: "NORMAL",
    name: "CSPD+80",
    view: `CSPD +80`,
  },
  {
    code: 102,
    link: null,
    type: "NORMAL",
    name: "",
    view: ``,
  },
  {
    code: 103,
    link: null,
    type: "NORMAL",
    name: "CSPD+60",
    view: `CSPD +60`,
  },
  {
    code: 104,
    link: null,
    type: "NORMAL",
    name: "CSPD+40",
    view: `CSPD +40`,
  },
  {
    code: 105,
    link: null,
    type: "NORMAL",
    name: "CSPD+20",
    view: `CSPD +20`,
  },
  {
    code: 106,
    link: null,
    type: "NORMAL",
    name: "Critical Rate+3",
    view: `Critical Rate +3`,
  },
  {
    code: 107,
    link: null,
    type: "NORMAL",
    name: "Critical Rate+2",
    view: `Critical Rate +2`,
  },
  {
    code: 108,
    link: null,
    type: "NORMAL",
    name: "",
    view: ``,
  },
  {
    code: 109,
    link: null,
    type: "NORMAL",
    name: "Critical Rate+1",
    view: `Critical Rate +1`,
  },
  {
    code: 110,
    link: null,
    type: "NORMAL",
    name: "Crimsosch",
    view: `AGI +3\nDodge +3\nCritical Rate -9\nEvasion Recharge +3%`,
  },
  {
    code: 111,
    link: null,
    type: "NORMAL",
    name: "Caspy",
    view: `Ailment Resistance -6%\nGuard Power +2%\nGuard Recharge +2%\nEvasion Recharge +2%`,
  },
  {
    code: 112,
    link: null,
    type: "NORMAL",
    name: "Boss Goblin",
    view: `ATK +1%\nAccuracy -4\nCritical Rate +2%`,
  },
  {
    code: 113,
    link: null,
    type: "NORMAL",
    name: "Big Coryn",
    view: `Physical Resistance+1%\nMagical Resistance +1%\nAilment Resistance +1%`,
  },
  {
    code: 114,
    link: null,
    type: "NORMAL",
    name: "",
    view: ``,
  },
  {
    code: 115,
    link: null,
    type: "NORMAL",
    name: "B.B. Goblin",
    view: `ATK +2%\nCritical Rate -1\nAggro +5%`,
  },
  {
    code: 116,
    link: null,
    type: "NORMAL",
    name: "Astol",
    view: `DEF -10%\nMagical Resistance +1%\nEvasion Recharge +3%`,
  },
  {
    code: 117,
    link: null,
    type: "NORMAL",
    name: "ASPD+80",
    view: `ASPD +80`,
  },
  {
    code: 118,
    link: null,
    type: "NORMAL",
    name: "ASPD+60",
    view: `ASPD +60`,
  },
  {
    code: 119,
    link: null,
    type: "NORMAL",
    name: "ASPD+40",
    view: `ASPD +40`,
  },
  {
    code: 120,
    link: null,
    type: "NORMAL",
    name: "",
    view: ``,
  },
  {
    code: 121,
    link: null,
    type: "NORMAL",
    name: "ASPD+20",
    view: `ASPD +20`,
  },
  {
    code: 122,
    link: null,
    type: "NORMAL",
    name: "Aranea",
    view: `MaxHP +400\nMaxMP +200\nAggro +1%`,
  },
  {
    code: 123,
    link: null,
    type: "NORMAL",
    name: "AGI+4",
    view: `AGI +4`,
  },
  {
    code: 124,
    link: null,
    type: "NORMAL",
    name: "AGI+3",
    view: `AGI +3`,
  },
  {
    code: 125,
    link: null,
    type: "NORMAL",
    name: "AGI+2",
    view: `AGI +2`,
  },
  {
    code: 126,
    link: null,
    type: "NORMAL",
    name: "",
    view: ``,
  },
  {
    code: 127,
    link: null,
    type: "NORMAL",
    name: "AGI+1",
    view: `AGI +1`,
  },
  {
    code: 128,
    link: null,
    type: "NORMAL",
    name: "Accuracy+8",
    view: `Accuracy +8`,
  },
  {
    code: 129,
    link: null,
    type: "NORMAL",
    name: "Accuracy+6",
    view: `Accuracy +6`,
  },
  {
    code: 130,
    link: null,
    type: "NORMAL",
    name: "Accuracy+4",
    view: `Accuracy +4`,
  },
  {
    code: 131,
    link: null,
    type: "NORMAL",
    name: "Boss Colon",
    view: `MaxHP +70\nMaxMP +30`,
  },
  {
    code: 132,
    link: null,
    type: "NORMAL",
    name: "",
    view: ``,
  },
  {
    code: 133,
    link: null,
    type: "NORMAL",
    name: "Accuracy +2",
    view: `Accuracy +2`,
  },
  {
    code: 134,
    link: null,
    type: "NORMAL",
    name: "Brutal Dragon Decel",
    view: `ATK +1%\nMATK +1%\nMaxMP -50`,
  },
  {
    code: 135,
    link: null,
    type: "NORMAL",
    name: "MP+250",
    view: `MaxMP +250`,
  },

  {
    code: 136,
    link: 229,
    type: "UPGRADE",
    name: "Don Profundo",
    view: `ATK +10%\nSTR +7%\nCritical Rate +8%\nDEF -27%`,
  },
  {
    code: 137,
    link: 286,
    type: "UPGRADE",
    name: "Capo Profundo",
    view: `Guard Recharge +8%\nPhysical Resistance +12%\nMaxHP +16%`,
  },
  {
    code: 138,
    link: 470,
    type: "UPGRADE",
    name: "Fantica",
    view: `MaxHP +500\nGuard Power +15%\nDEF +10%`,
  },
  {
    code: 139,
    link: 22,
    type: "UPGRADE",
    name: "Red Ash Dragon Rudis",
    view: `Short Range Damage +9%\nAccuracy +5%\nMaxMP +200\nCritical Rate -7\nMaxHP -300`,
  },
  {
    code: 140,
    link: null,
    type: "UPGRADE",
    name: "",
    view: ``,
  },
  {
    code: 141,
    link: 364,
    type: "UPGRADE",
    name: "Zapo",
    view: `ATK +10%\nCritical Rate +10\nMaxHP -400\nMaxMP -400\nWith Shield:\nShort Range Damage +5%\nSTR +1%`,
  },
  {
    code: 142,
    link: 33,
    type: "UPGRADE",
    name: "Kuffania",
    view: `Short Range Damage +4%\nStability +4%\nEvasion Recharge +4%\nLong Range Damage -12%`,
  },
  {
    code: 143,
    link: 208,
    type: "UPGRADE",
    name: "Eripmav",
    view: `Attack MP Recovery +18\nFire resistance +12%\nCritical Damage +6`,
  },
  {
    code: 144,
    link: 358,
    type: "UPGRADE",
    name: "Dr. Leonardo II",
    view: `MATK +3%\nLong Range Damage +6%\nCritical Rate +20%\nMaxHP +6000\nResistansi Status Buruk +5%`,
  },
  {
    code: 145,
    link: 360,
    type: "UPGRADE",
    name: "DX Fighter II",
    view: `ATK +3%\nShort Range Damage +6%\nAccuracy +15%\nMaxHP +6000\nFractional Barrier +5%`,
  },
  {
    code: 146,
    link: null,
    type: "UPGRADE",
    name: "",
    view: ``,
  },
  {
    code: 147,
    link: 409,
    type: "UPGRADE",
    name: "Etoise",
    view: `Critical Rate +40%\nkecepatan Serangan +1100\nMotion Speed +5%\nCSPD -70%`,
  },
  {
    code: 148,
    link: 287,
    type: "UPGRADE",
    name: "Dominaredor",
    view: `ATK +8%\nMATK +8%\nASPD +20%\nReduksi DMG (Lantai) +20%`,
  },
  {
    code: 149,
    link: 241,
    type: "UPGRADE",
    name: "Lilicarolla",
    view: `Unsheathe Attack +18%\nDodge -5%\nMaxMP -100`,
  },
  {
    code: 150,
    link: 225,
    type: "UPGRADE",
    name: "Baavgai",
    view: `MaxHP +7000\nCritical Damage +7\nShort Range Damage +5%`,
  },
  {
    code: 151,
    link: 93,
    type: "UPGRADE",
    name: "Charugon",
    view: `STR +6\nShort Range Damage +3%\nLong Range Damage +6%\nMagical Resistance -12%`,
  },
  {
    code: 152,
    link: null,
    type: "UPGRADE",
    name: "",
    view: ``,
  },
  {
    code: 153,
    link: 247,
    type: "UPGRADE",
    name: "Brass Dragon Reguita",
    view: `ATK +10%\nMATK +10%\nNatural HP Regen -12%\nNatural MP Regen -12%`,
  },
  {
    code: 154,
    link: 361,
    type: "UPGRADE",
    name: "Kruztor II",
    view: `MaxHP +7%\nDodge +7%\nPhysical Resistance +7%\nMagical Resistance +7%\nNeutral Resistance +7%`,
  },
  {
    code: 155,
    link: 204,
    type: "UPGRADE",
    name: "Walican",
    view: `MaxHP +6000\nWeapon ATK +6%`,
  },
  {
    code: 156,
    link: 37,
    type: "UPGRADE",
    name: "Orictoceras",
    view: `Critical Damage +9\nReduksi DMG (Sekitar Pemain) -3%\nReduksi DMG (Sekitar Musuh) -3%`,
  },
  {
    code: 157,
    link: 246,
    type: "UPGRADE",
    name: "Sicanokami",
    view: `Short Range Damage +5%\nAttack MP Recovery +20\nAccuracy +50\nWith Halberd:\nLong Range Damage +5%`,
  },
  {
    code: 158,
    link: null,
    type: "UPGRADE",
    name: "",
    view: ``,
  },
  {
    code: 159,
    link: 478,
    type: "UPGRADE",
    name: "Chocolate Ooze II",
    view: `MaxHP -15%\nMaxMP +300\nCSPD +600`,
  },
  {
    code: 160,
    link: 268,
    type: "UPGRADE",
    name: "Amargon",
    view: `Kecepatan Serang +800\nMaxHP +30%\nMaxMP +300`,
  },
  {
    code: 161,
    link: 162,
    type: "UPGRADE",
    name: "Megiston The Champion V",
    view: `MaxHP +1800\nCritical Rate +23\nFire resistance +6%\nWater resistance +6%\nWind resistance +3%\nEarth resistance +3%\nLight resistance +3%`,
  },
  {
    code: 162,
    link: 163,
    type: "UPGRADE",
    name: "Megiston The Champion IV",
    view: `MaxHP +1600\nCritical Rate +20\nFire resistance +6%\nWater resistance +3%\nWind resistance +3%\nLight resistance +3%`,
  },
  {
    code: 163,
    link: 165,
    type: "UPGRADE",
    name: "Megiston The Champion III",
    view: `MaxHP +1400\nCritical Rate +18\nFire resistance +3%\nWind resistance +3%\nLight resistance +3%`,
  },
  {
    code: 164,
    link: null,
    type: "UPGRADE",
    name: "",
    view: ``,
  },
  {
    code: 165,
    link: 328,
    type: "UPGRADE",
    name: "Megiston The Champion II",
    view: `MaxHP +1200\nCritical Rate +16\nFire resistance +3%\nLight resistance +3%`,
  },
  {
    code: 166,
    link: 213,
    type: "UPGRADE",
    name: "Zega VII",
    view: `MaxHP +1000\nAttack MP Recovery +9\nMagical Resistance +8%\nWater resistance +7%`,
  },
  {
    code: 167,
    link: 386,
    type: "UPGRADE",
    name: "Goleps",
    view: `MaxMP +250\nMaxHP +750`,
  },
  {
    code: 168,
    link: 322,
    type: "UPGRADE",
    name: "Guardkissa Cat Claw",
    view: `ATK +10%\nAGI +4%\nAilment Resistance +2%\nAttack MP Recovery +2\nMaxHP -12%`,
  },
  {
    code: 169,
    link: 171,
    type: "UPGRADE",
    name: "Goldigem",
    view: `MaxHP +3000\nReduksi DMG (Terjang) +10%\nReduksi DMG (Linear) +10%\nReduksi DMG (Sekitar Pemain) +10%`,
  },
  {
    code: 170,
    link: null,
    type: "UPGRADE",
    name: "",
    view: ``,
  },
  {
    code: 171,
    link: 460,
    type: "UPGRADE",
    name: "Felicitoad",
    view: `MaxHP +2000\nReduksi DMG (Terjang) +10%\nReduksi DMG (Linear) +10%`,
  },
  {
    code: 172,
    link: 250,
    type: "UPGRADE",
    name: "Crysmort",
    view: `Attack MP Recovery +11\nMaxHP +3000\nStability +1%`,
  },
  {
    code: 173,
    link: 279,
    type: "UPGRADE",
    name: "Neo Wandering Wheel",
    view: `Long Range Damage -16%\nMATK +5%\nCSPD +75%`,
  },
  {
    code: 174,
    link: 67,
    type: "UPGRADE",
    name: "Nuthoreth",
    view: `ATK +2%\nMATK +2%\nASPD +150\nCSPD +150`,
  },
  {
    code: 175,
    link: 468,
    type: "UPGRADE",
    name: "Jeila",
    view: `Attack MP Recovery +6\nFire resistance +4%\nCritical Damage +2`,
  },
  {
    code: 176,
    link: null,
    type: "UPGRADE",
    name: "",
    view: ``,
  },
  {
    code: 177,
    link: 370,
    type: "UPGRADE",
    name: "Black Velly",
    view: `MaxHP +3000\nMaxMP +400\nMATK +9%\nEvasion Recharge -20%`,
  },
  {
    code: 178,
    link: 323,
    type: "UPGRADE",
    name: "Florizard",
    view: `Stability +5%\nMagic Pierce +20%\nAggro -15%`,
  },
  {
    code: 179,
    link: 325,
    type: "UPGRADE",
    name: "Pedrio",
    view: `ATK +10%\nMATK +10%\nReduksi DMG (Bowling) +20%\nReduksi DMG (Peluru) +20%\nAggro -40%`,
  },
  {
    code: 180,
    link: 226,
    type: "UPGRADE",
    name: "Hero Potum III",
    view: `MaxHP +12%\nFractional Barrier +14%\nAccuracy +16%\nAggro +18%`,
  },
  {
    code: 181,
    link: 329,
    type: "UPGRADE",
    name: "Pomie Chan II",
    view: `ATK +9%\nAGI +7%\nAggro -15%\nWith Knuckle:\nDodge Absolut +5%\n`,
  },
  {
    code: 182,
    link: null,
    type: "UPGRADE",
    name: "",
    view: ``,
  },
  {
    code: 183,
    link: 465,
    type: "UPGRADE",
    name: "Baphomela",
    view: `Short Range Damage +6%\nLong Range Damage +6%\nSerangan menghunus +6%`,
  },
  {
    code: 184,
    link: 238,
    type: "UPGRADE",
    name: "Wicked Dragon Fazzino",
    view: `MATK +9%\nDEX +7%\nCSPD +5%`,
  },
  {
    code: 185,
    link: 372,
    type: "UPGRADE",
    name: "Filrocas",
    view: `MaxHP +60%\nMagical Resistance -7%\nPhysical Resistance -7%\nWith Knuckle:\nAggro +15%\nWith One Hand Sword:\nAggro +15%`,
  },
  {
    code: 186,
    link: 477,
    type: "UPGRADE",
    name: "Exdocus",
    view: `DEF +150\nMDEF +150\nPhysical Barrier +1500\nMagic Barrier +1500`,
  },
  {
    code: 187,
    link: 294,
    type: "UPGRADE",
    name: "Brassozard",
    view: `STR +3%\nATK +3%\nAccuracy -10%\nCritical Rate -10%\nCritical Damage +3`,
  },
  {
    code: 188,
    link: null,
    type: "UPGRADE",
    name: "",
    view: ``,
  },
  {
    code: 189,
    link: 265,
    type: "UPGRADE",
    name: "Burning Dragon Igneus",
    view: `AGI +3%\nCritical Rate +15\nCritical Damage +8`,
  },
  {
    code: 190,
    link: 373,
    type: "UPGRADE",
    name: "Galegon",
    view: `CSPD +20%\nAggro -30%\nFractional Barrier +10%`,
  },
  {
    code: 191,
    link: 289,
    type: "UPGRADE",
    name: "Guard Golem",
    view: `ATK +9%\nMATK +9%\nASPD -225\nCSPD -225`,
  },
  {
    code: 192,
    link: 274,
    type: "UPGRADE",
    name: "Gordel",
    view: `MaxMP +800\nFractional Barrier +17%\nCritical Rate +3`,
  },
  {
    code: 193,
    link: 264,
    type: "UPGRADE",
    name: "Oculasignio",
    view: `MaxMP +300\nMATK +9%\nGuard Break +13%`,
  },
  {
    code: 194,
    link: null,
    type: "UPGRADE",
    name: "",
    view: ``,
  },
  {
    code: 195,
    link: 385,
    type: "UPGRADE",
    name: "Glaucius",
    view: `Evasion Recharge +15%\nMagical Resistance +6%\nMATK +6%\nWith Light Armor:\nMATK UP (AGI25%\n)`,
  },
  {
    code: 196,
    link: 243,
    type: "UPGRADE",
    name: "Trickster Dragon Mimyugon",
    view: `ATK +9%\nDEX +7%\nASPD +5%`,
  },
  {
    code: 197,
    link: 443,
    type: "UPGRADE",
    name: "Garnache",
    view: `MaxHP +18%\nMATK +3%\nMagic Pierce +10%\nAggro -15%`,
  },
  {
    code: 198,
    link: 269,
    type: "UPGRADE",
    name: "Velum",
    view: `ATK +9%\nAttack MP Recovery +6\nAnticipate 13%\nMaxMP -100`,
  },
  {
    code: 199,
    link: 122,
    type: "UPGRADE",
    name: "Blazingur",
    view: `MaxHP +600\nMaxMP +300\nAggro +2%`,
  },
  {
    code: 200,
    link: null,
    type: "UPGRADE",
    name: "",
    view: ``,
  },
  {
    code: 201,
    link: 293,
    type: "UPGRADE",
    name: "Vlam the Flame Dragon",
    view: `MaxMP +400\nShort Range Damage +6%\nPhysical Pierce +7%`,
  },
  {
    code: 202,
    link: 481,
    type: "UPGRADE",
    name: "Melancia",
    view: `Stability +5%\nAccuracy +5%\nCritical Rate +5%`,
  },
  {
    code: 203,
    link: 183,
    type: "UPGRADE",
    name: "Prudent Blue Shadow",
    view: `Short Range Damage +8%\nLong Range Damage +8%\nUnsheathe Attack +8%\nMaxMP -150`,
  },
  {
    code: 204,
    link: 252,
    type: "UPGRADE",
    name: "Ferzen the Rock Dragon",
    view: `MaxHP +5000\nWeaponATK +5%`,
  },
  {
    code: 205,
    link: 271,
    type: "UPGRADE",
    name: "War Dragon Turba",
    view: `Critical Rate +11\nWeapon Attack +14%\nAccuracy +17%\nMaxMP -200`,
  },
  {
    code: 206,
    link: null,
    type: "UPGRADE",
    name: "",
    view: ``,
  },
  {
    code: 207,
    link: 279,
    type: "UPGRADE",
    name: "Gordo",
    view: `Long Range Damage -15%\nATK +7%\nASPD +80%`,
  },
  {
    code: 208,
    link: 259,
    type: "UPGRADE",
    name: "Neewollah",
    view: `Attack MP Recovery +15\nFire resistance +10%\nCritical Damage +5`,
  },
  {
    code: 209,
    link: 301,
    type: "UPGRADE",
    name: "Bullamius",
    view: `MP +250\nATK +3%\nMATK +3%`,
  },
  {
    code: 210,
    link: 431,
    type: "UPGRADE",
    name: "Teertocrit",
    view: `ATK +6%\nMATK +6%\nMotion Speed +2%`,
  },
  {
    code: 211,
    link: 280,
    type: "UPGRADE",
    name: "Usamochi",
    view: `MaxMP +300\nATK +6%\nUnsheathe Attack +6%\nNeutral Resistance -10%`,
  },
  {
    code: 212,
    link: null,
    type: "UPGRADE",
    name: "",
    view: ``,
  },
  {
    code: 213,
    link: 237,
    type: "UPGRADE",
    name: "Zega VI",
    view: `MaxHP +900\nAttack MP Recovery +8\nMagical Resistance +7%\nWater resistance +6%`,
  },
  {
    code: 214,
    link: 367,
    type: "UPGRADE",
    name: "Yuveria",
    view: `MaxMP+300\nPhysical Resistance +3%\nMagical Resistance +3%\nShort Range Damage +6%\nAggro -15%`,
  },
  {
    code: 215,
    link: 333,
    type: "UPGRADE",
    name: "Clawed Iron Witch",
    view: `Short Range Damage +5%\nAttack MP Recovery +10\nPhysical Barrier +2000\nMagic Barrier +2000`,
  },
  {
    code: 216,
    link: 258,
    type: "UPGRADE",
    name: "Gemma",
    view: `Unsheathe Attack +7%\nPhysical Pierce +5%\nCritical Damage +6`,
  },
  {
    code: 217,
    link: 74,
    type: "UPGRADE",
    name: "Rhinosaurus",
    view: `MaxHP +10%\nASPD +15%\nATK +5%`,
  },
  {
    code: 218,
    link: null,
    type: "UPGRADE",
    name: "",
    view: ``,
  },
  {
    code: 219,
    link: 446,
    type: "UPGRADE",
    name: "Royal Ox King",
    view: `Short Range Damage +8%\nAccuracy +40\nMaxMP +200\nMaxHP -20%`,
  },
  {
    code: 220,
    link: 446,
    type: "UPGRADE",
    name: "Pillow Kitagawa",
    view: `Unsheathe Attack +8%\nCritical Rate +4\nMaxHP +2000\nRevive Time +20%`,
  },
  {
    code: 221,
    link: 282,
    type: "UPGRADE",
    name: "Irestida",
    view: `MATK +8%\nMagic Pierce +6%\nAggro -9%\nMDEF -24%`,
  },
  {
    code: 222,
    link: 476,
    type: "UPGRADE",
    name: "Trocostida",
    view: `MaxHP +20%\nCritical Rate +5\nAggro +15%\nLong Range Damage -10%`,
  },
  {
    code: 223,
    link: 456,
    type: "UPGRADE",
    name: "Alfenix",
    view: `ATK +3%\nPhysical Pierce +10%\nMaxHP +18%\nAggro -15%`,
  },
  {
    code: 224,
    link: null,
    type: "UPGRADE",
    name: "",
    view: ``,
  },
  {
    code: 225,
    link: 267,
    type: "UPGRADE",
    name: "Dreamy Scarlet Sakura",
    view: `MaxHP +4000\nCritical Damage +4\nShort Range Damage +2%`,
  },
  {
    code: 226,
    link: 331,
    type: "UPGRADE",
    name: "Hero Potum II",
    view: `MaxHP +11%\nFractional Barrier +12%\nAccuracy +13%\nAggro +14%`,
  },
  {
    code: 227,
    link: 228,
    type: "UPGRADE",
    name: "✝Dark Lord✝",
    view: `ATK +5%\nShort Range Damage +3%\nASPD +20%\nAggro -10%`,
  },
  {
    code: 228,
    link: 454,
    type: "UPGRADE",
    name: "Yashiro Azuki Mom II",
    view: `MATK +5%\nLong Range Damage +3%\nCSPD +20%\nAggro -10%`,
  },
  {
    code: 229,
    link: 292,
    type: "UPGRADE",
    name: "Hexter",
    view: `ATK +8%\nSTR +6%\nCritical Rate +6%\nDEF -21%`,
  },
  {
    code: 230,
    link: null,
    type: "UPGRADE",
    name: "",
    view: ``,
  },
  {
    code: 231,
    link: 263,
    type: "UPGRADE",
    name: "Black Shadow",
    view: `ATK +8%\nMATK +8%\nAttack MP Recovery+3\nMaxMP -150`,
  },
  {
    code: 232,
    link: 443,
    type: "UPGRADE",
    name: "Gernache",
    view: `MATK +3%\nMagic Pierce +10%\nMaxHP +18%\nAggro -15%`,
  },
  {
    code: 233,
    link: 461,
    type: "UPGRADE",
    name: "Stellar Ooze",
    view: `Critical Rate +20\nAccuracy +60\nMaxMP +300\nCSPD +600`,
  },
  {
    code: 234,
    link: 273,
    type: "UPGRADE",
    name: "Yule Cat",
    view: `MATK +7%\nINT +3%\nCSPD +35%\nAttack MP Recovery +10%`,
  },
  {
    code: 235,
    link: 423,
    type: "UPGRADE",
    name: "Espectro",
    view: `Attack MP Recovery +4\nATK +2%\nMATK +2%\nCritical Damage +2%`,
  },
  {
    code: 236,
    link: null,
    type: "UPGRADE",
    name: "",
    view: ``,
  },
  {
    code: 237,
    link: 257,
    type: "UPGRADE",
    name: "Zega V",
    view: `MaxHP +800\nAttack MP Recovery +7\nMagical Resistance +6%\nWater resistance +5%`,
  },
  {
    code: 238,
    link: 295,
    type: "UPGRADE",
    name: "Pisteus",
    view: `MATK +7%\nDEX +5%\nCSPD +3%`,
  },
  {
    code: 239,
    link: 291,
    type: "UPGRADE",
    name: "Ageladanios",
    view: `ATK +6%\nCritical Damage +8\nMotion Speed -1%\nMagical Resistance -15%`,
  },
  {
    code: 240,
    link: 418,
    type: "UPGRADE",
    name: "Venena II",
    view: `MaxMP +600\nATK +2%\nMATK +2%\nStability +3%`,
  },
  {
    code: 241,
    link: 50,
    type: "UPGRADE",
    name: "Tappler",
    view: `Unsheathe Attack +12%\nDodge -5%\nEvasion Recharge -3%\nMaxMP -50`,
  },
  {
    code: 242,
    link: null,
    type: "UPGRADE",
    name: "",
    view: ``,
  },
  {
    code: 243,
    link: 298,
    type: "UPGRADE",
    name: "Vulture",
    view: `ATK +7%\nDEX +5%\nASPD +3%`,
  },
  {
    code: 244,
    link: 421,
    type: "UPGRADE",
    name: "Sand Bandits Leader",
    view: `Evasion Recharge +8%\nAggro +16%\nMATK -5%`,
  },
  {
    code: 245,
    link: 467,
    type: "UPGRADE",
    name: "Tardigrademon",
    view: `CSPD +450\nMaxMP -200`,
  },
  {
    code: 246,
    link: 300,
    type: "UPGRADE",
    name: "Patissia",
    view: `Attack MP Recovery +15\nAccuracy +25`,
  },
  {
    code: 247,
    link: 335,
    type: "UPGRADE",
    name: "Repthon",
    view: `ATK +6%\nMATK +6%\nNatural MP Regen -10%\nNatural HP Regen -10%`,
  },
  {
    code: 248,
    link: null,
    type: "UPGRADE",
    name: "",
    view: ``,
  },
  {
    code: 249,
    link: 368,
    type: "UPGRADE",
    name: "Demonic Eye",
    view: `MaxHP +1000\nASPD +300\nTumble Unavailable`,
  },
  {
    code: 250,
    link: 299,
    type: "UPGRADE",
    name: "Amalgam",
    view: `Attack MP Recovery +9\nMaxHP +2000`,
  },
  {
    code: 251,
    link: 348,
    type: "UPGRADE",
    name: "Blood Smeared Crystal",
    view: `Attack MP Recovery +7\nCritical Damage +6\nAggro +10%`,
  },
  {
    code: 252,
    link: 277,
    type: "UPGRADE",
    name: "Sapphire Roga",
    view: `MaxHP +4000\nWeapon ATK +4%`,
  },
  {
    code: 253,
    link: 474,
    type: "UPGRADE",
    name: "Mega Alpoca",
    view: `Short Range Damage +6%\nMaxHP +300\nMaxMP +300`,
  },
  {
    code: 254,
    link: null,
    type: "UPGRADE",
    name: "",
    view: ``,
  },
  {
    code: 255,
    link: 336,
    type: "UPGRADE",
    name: "Zega II",
    view: `MaxHP +500\nAttack MP Recovery +4\nMagical Resistance +3%\nWater resistance +2%`,
  },
  {
    code: 256,
    link: 255,
    type: "UPGRADE",
    name: "Zega III",
    view: `MaxHP +600\nAttack MP Recovery +5\nMagical Resistance +4%\nWater resistance +3%`,
  },
  {
    code: 257,
    link: 256,
    type: "UPGRADE",
    name: "Zega IV",
    view: `MaxHP +700\nAttack MP Recovery +6\nMagical Resistance +5%\nWater resistance +4%`,
  },
  {
    code: 258,
    link: 387,
    type: "UPGRADE",
    name: "Pyxtica",
    view: `Unsheathe Attack +4%\nPhysical Pierce +4%\nCritical Damage +4`,
  },
  {
    code: 259,
    link: 276,
    type: "UPGRADE",
    name: "Zarth",
    view: `Attack MP Recovery +12\nFire resistance +8%\nCritical Damage +4`,
  },
  {
    code: 260,
    link: null,
    type: "UPGRADE",
    name: "",
    view: ``,
  },
  {
    code: 261,
    link: 330,
    type: "UPGRADE",
    name: "Usasama the Necromancer II",
    view: `MATK +7%\nCSPD +14%\nMotion Speed +3%\nMaxHP -15%\nAttack MP Recovery -30%`,
  },
  {
    code: 262,
    link: 346,
    type: "UPGRADE",
    name: "Giant Moon Crab",
    view: `ATK +6%\nVIT +4%\nMotion Speed +1%`,
  },
  {
    code: 263,
    link: 297,
    type: "UPGRADE",
    name: "Tuscog",
    view: `ATK +6%\nMATK +6%\nAttack MP Recovery +2\nMaxMP -100`,
  },
  {
    code: 264,
    link: 345,
    type: "UPGRADE",
    name: "Finstern the Dark Dragon",
    view: `MATK +7%\nMaxMP +300\nGuard Break +12%`,
  },
  {
    code: 265,
    link: 303,
    type: "UPGRADE",
    name: "King Piton",
    view: `Critical Rate +10\nCritical Damage +4`,
  },
  {
    code: 266,
    link: null,
    type: "UPGRADE",
    name: "",
    view: ``,
  },
  {
    code: 267,
    link: 388,
    type: "UPGRADE",
    name: "Mimesia",
    view: `MaxHP +2000\nCritical Damage +2`,
  },
  {
    code: 268,
    link: 479,
    type: "UPGRADE",
    name: "Candela II",
    view: `MaxHP +20%\nMaxMP -250\nASPD +600`,
  },
  {
    code: 269,
    link: 353,
    type: "UPGRADE",
    name: "Mardula",
    view: `ATK +7%\nAttack MP Recovery +4\nAnticipate +12%`,
  },
  {
    code: 270,
    link: 343,
    type: "UPGRADE",
    name: "Bubble Bogey",
    view: `Additional Magic +125%\nCSPD +200\nMagic Barrier +200`,
  },
  {
    code: 271,
    link: 433,
    type: "UPGRADE",
    name: "Zelbuse",
    view: `Critical Rate +8\nWeapon ATK +12%\nAccuracy +16%\nMaxMP -150`,
  },
  {
    code: 272,
    link: null,
    type: "UPGRADE",
    name: "",
    view: ``,
  },
  {
    code: 273,
    link: 375,
    type: "UPGRADE",
    name: "Noeliel the Ice Statue",
    view: `MATK +5%\nCSPD +30%\nAttack MP Recovery +10%`,
  },
  {
    code: 274,
    link: 384,
    type: "UPGRADE",
    name: "Mom Fluck",
    view: `MaxMP +700\nFractional Barrier +15%`,
  },
  {
    code: 275,
    link: 80,
    type: "UPGRADE",
    name: "Platinum Potum",
    view: `MaxHP +20%\nPhysical Resistance -10%\nMagical Resistance -10%`,
  },
  {
    code: 276,
    link: 175,
    type: "UPGRADE",
    name: "Zoe",
    view: `Attack MP Recovery +9\nFire resistance +6%\nCritical Damage +3`,
  },
  {
    code: 277,
    link: 305,
    type: "UPGRADE",
    name: "Ornlarf",
    view: `MaxHP +3000\nWeapon ATK +3%`,
  },
  {
    code: 278,
    link: null,
    type: "UPGRADE",
    name: "",
    view: ``,
  },
  {
    code: 279,
    link: 471,
    type: "UPGRADE",
    name: "Wandering Wheel",
    view: `ATK +5%\nASPD +75%\nLong Range Damage -14%`,
  },
  {
    code: 280,
    link: 379,
    type: "UPGRADE",
    name: "Usami",
    view: `MaxMP +300\nATK +3%\nUnsheathe Attack +3%\nNeutral Resistance -10%`,
  },
  {
    code: 281,
    link: 473,
    type: "UPGRADE",
    name: "Solopy",
    view: `ASPD +450\nMaxHP -15%`,
  },
  {
    code: 282,
    link: 354,
    type: "UPGRADE",
    name: "Shampy",
    view: `MATK +6%\nMagic Pierce +5%\nAggro -7%\nMDEF -18%`,
  },
  {
    code: 283,
    link: 110,
    type: "UPGRADE",
    name: "Amoeba Machina",
    view: `AGI +6\nDodge +5\nEvasion Recharge +4%\nCritical Rate -6`,
  },
  {
    code: 284,
    link: null,
    type: "UPGRADE",
    name: "",
    view: ``,
  },
  {
    code: 285,
    link: 113,
    type: "UPGRADE",
    name: "Seraph Machina",
    view: `Ailment Resistance +3%\nPhysical Resistance +3%\nMagical Resistance +3%`,
  },
  {
    code: 286,
    link: 381,
    type: "UPGRADE",
    name: "Daddy Finpen",
    view: `MaxHP +6%\nGuard Rate +6%\nPhysical Resistance +6%`,
  },
  {
    code: 287,
    link: 424,
    type: "UPGRADE",
    name: "Lalvada",
    view: `ATK +4%\nMATK +4%\nDEF -4%\nMDEF-4%`,
  },
  {
    code: 288,
    link: 382,
    type: "UPGRADE",
    name: "Super Death Mushroom",
    view: `MaxMP +400\nCSPD +200\nAttack MP Recovery +3`,
  },
  {
    code: 289,
    link: 67,
    type: "UPGRADE",
    name: "Guignol",
    view: `ATK +5%\nMATK +5%\nASPD -175\nCSPD -175`,
  },
  {
    code: 290,
    link: null,
    type: "UPGRADE",
    name: "",
    view: ``,
  },
  {
    code: 291,
    link: 75,
    type: "UPGRADE",
    name: "Lyark Master Specialist",
    view: `ATK +3%\nCritical Damage +4\nKebal Sihir -15%\nMotion Speed -2%`,
  },
  {
    code: 292,
    link: 352,
    type: "UPGRADE",
    name: "Gwaimol",
    view: `ATK +6%\nSTR +5%\nCritical Rate +4%\nDEF -15%`,
  },
  {
    code: 293,
    link: 337,
    type: "UPGRADE",
    name: "Ultimate Machina",
    view: `MaxMP +400\nPhysical Pierce +4%\nShort Range Damage +4%`,
  },
  {
    code: 294,
    link: 51,
    type: "UPGRADE",
    name: "Volotur",
    view: `ATK +2%\nSTR +2%\nCritical Damage +2\nAccuracy -10%\nCritical Rate -10%`,
  },
  {
    code: 295,
    link: 349,
    type: "UPGRADE",
    name: "Mozto Machina",
    view: `DEX +4%\nMATK +6%\nCSPD +2%`,
  },
  {
    code: 296,
    link: null,
    type: "UPGRADE",
    name: "",
    view: ``,
  },
  {
    code: 297,
    link: 134,
    type: "UPGRADE",
    name: "York",
    view: `ATK +4%\nMATK +4%\nAttack MP Recovery +1\nMaxMP -75`,
  },
  {
    code: 298,
    link: 346,
    type: "UPGRADE",
    name: "Tyrant Machina",
    view: `ATK +6%\nDEX +4%\nASPD +2%`,
  },
  {
    code: 299,
    link: 419,
    type: "UPGRADE",
    name: "Deniala",
    view: `MaxHP +1000\nAttack MP Recovery +6`,
  },
  {
    code: 300,
    link: 429,
    type: "UPGRADE",
    name: "Tapir",
    view: `Attack MP Recovery +10`,
  },
  {
    code: 301,
    link: 91,
    type: "UPGRADE",
    name: "Salamander",
    view: `MaxMP +200\nATK +1%\nMATK +1%`,
  },
  {
    code: 302,
    link: null,
    type: "UPGRADE",
    name: "",
    view: ``,
  },
  {
    code: 303,
    link: 464,
    type: "UPGRADE",
    name: "Proto Leon",
    view: `Critical Rate +8\nCritical Damage +3`,
  },
  {
    code: 304,
    link: 422,
    type: "UPGRADE",
    name: "Memecoleous",
    view: `ATK -4%\nGuard Recharge +5%\nAggro +12%`,
  },
  {
    code: 305,
    link: 390,
    type: "UPGRADE",
    name: "Iconos",
    view: `MaxHP +2000\nWeapon ATK +2%`,
  },
  {
    code: 306,
    link: 347,
    type: "UPGRADE",
    name: "Builder Golem",
    view: `Guard Power +7%\nGuard Recharge +7%`,
  },
  {
    code: 307,
    link: 480,
    type: "UPGRADE",
    name: "Ancient Empress II",
    view: `MATK +5%\nCSPD +30%\nShort Range Damage -20%`,
  },
  {
    code: 308,
    link: null,
    type: "UPGRADE",
    name: "",
    view: ``,
  },
  {
    code: 309,
    link: 449,
    type: "UPGRADE",
    name: "Underwater Ruins Monster",
    view: `MATK+8%\nCritical Damage +8\nMaxHP +1000\nWith Heavy Armor:\nAggro +20%`,
  },
  {
    code: 310,
    link: null,
    type: "WEAPON",
    name: "Primordial Moonlit",
    view: `ATK +10%\nMATK +10%\nMaxHP +10%\nAnticipate +10%\nGuard Break +10%\nMaxMP -200`,
  },
  {
    code: 311,
    link: null,
    type: "WEAPON",
    name: "Cursed Crysta",
    view: `ATK +5%\nMATK +5%\nStability +5%\nMotion Speed +5%\nRecoil +20%`,
  },
  {
    code: 312,
    link: null,
    type: "WEAPON",
    name: "Xmas Princess in Black",
    view: `ATK +9%\nMATK +9%\nSTR +3%\nINT +3%\nLong Range Damage -6%\nTumble Unavailable\With Shield:\nAggro -50%`,
  },
  {
    code: 313,
    link: null,
    type: "WEAPON",
    name: "Midsummer Passion",
    view: `MaxHP +15%\nCritical Rate +20\nFire resistance +25%\nRecoil +3,00%`,
  },
  {
    code: 314,
    link: null,
    type: "WEAPON",
    name: "",
    view: ``,
  },
  {
    code: 315,
    link: null,
    type: "WEAPON",
    name: "Crimson One-Eyed Wolf",
    view: `Short Range Damage +8%\nAnticipate +4%\nPhysical Resistance -16%\nMagical Resistance -8%\nWith Dagger:\nCritical Damage +1%\nWith Dual Sword:\nAggro -20%`,
  },
  {
    code: 316,
    link: null,
    type: "WEAPON",
    name: "Arbogazella",
    view: `Long Range Damage +7%\nAccuracy +14%\nMaxHP -28%`,
  },
  {
    code: 317,
    link: null,
    type: "WEAPON",
    name: "Devil Dango",
    view: `ATK +4%\nPhysical Pierce +20%\nAggro -10%\nResistansi Status Buruk -15%\nMaxMP -200`,
  },
  {
    code: 318,
    link: null,
    type: "WEAPON",
    name: "Lil Wonder Rat",
    view: `Long Range Damage +4%\nUnsheathe Attack +4%\nAggro -20%\nWith Staff:\MATK +6%`,
  },
  {
    code: 319,
    link: null,
    type: "WEAPON",
    name: "Jeandoux",
    view: `Critical Damage +7\nSTR +3%\nAggro -10%`,
  },
  {
    code: 320,
    link: null,
    type: "WEAPON",
    name: "",
    view: ``,
  },
  {
    code: 321,
    link: null,
    type: "WEAPON",
    name: "Kuzto",
    view: `MATK +7%\nCritical Rate +7\nAggro -7%`,
  },
  {
    code: 322,
    link: null,
    type: "WEAPON",
    name: "Blancanine the White Fang",
    view: `ATK +7%\nAGI +4%\nAttack MP Recovery +1\nMaxHP -12%`,
  },
  {
    code: 323,
    link: null,
    type: "WEAPON",
    name: "Armasite",
    view: `MATK +5%\nMagic Pierce +20%\nCSPD -15%`,
  },
  {
    code: 324,
    link: null,
    type: "WEAPON",
    name: "Drama Clown",
    view: `Accuracy +10%\nCritical Rate +10\nASPD +200\nCSPD +200`,
  },
  {
    code: 325,
    link: null,
    type: "WEAPON",
    name: "Neo Maton Sword",
    view: `ATK +7%\nMATK +7%\nReduksi DMG (Bowling) +14%\nReduksi DMG (Peluru) +14%\nAggro -28%`,
  },
  {
    code: 326,
    link: null,
    type: "WEAPON",
    name: "",
    view: ``,
  },
  {
    code: 327,
    link: null,
    type: "WEAPON",
    name: "Grecia",
    view: `ATK +6%\nMATK +6%\nPhysical Pierce +3%\nMagic Pierce +3%`,
  },
  {
    code: 328,
    link: null,
    type: "WEAPON",
    name: "Megiston the Champion",
    view: `MaxHP +1000\nCritical Rate +15\nFire resistance +3%`,
  },
  {
    code: 329,
    link: null,
    type: "WEAPON",
    name: "Pomie Chan",
    view: `ATK +5%\nAGI +5%\nAggro -5%\nWith Knuckle:\nDodge Absolut +5%`,
  },
  {
    code: 330,
    link: null,
    type: "WEAPON",
    name: "Usasama the Necromancer",
    view: `MATK +6%\nCSPD +12%\nMotion Speed +3%\nMaxHP -25%\nAttack MP Recovery -50%`,
  },
  {
    code: 331,
    link: null,
    type: "WEAPON",
    name: "Hero Potum",
    view: `MaxHP +10%\nFractional Barrier +10%\nAccuracy +10%\nAggro +10%`,
  },
  {
    code: 332,
    link: null,
    type: "WEAPON",
    name: "",
    view: ``,
  },
  {
    code: 333,
    link: null,
    type: "WEAPON",
    name: "Zahhak Machina",
    view: `Attack MP Recovery +5\nPhysical Barrier +1000\nMagical Barrier +1000`,
  },
  {
    code: 334,
    link: null,
    type: "WEAPON",
    name: "Commander Golem",
    view: `ASPD +100\nPhysical Barrier +100\nAdditional Melee +100%`,
  },
  {
    code: 335,
    link: null,
    type: "WEAPON",
    name: "Zolban",
    view: `Natural HP Regen -10%\nNatural MP Regen -10%\nATK +4%\nMATK +4%`,
  },
  {
    code: 336,
    link: null,
    type: "WEAPON",
    name: "Zega",
    view: `MaxHP +400\nMagical Resistance +2%\nWater resistance +1%\nAttack MP Recovery +3`,
  },
  {
    code: 337,
    link: null,
    type: "WEAPON",
    name: "Pillar Golem",
    view: `MaxMP +300\nPhysical Pierce +3%\nShort Range Damage +3%`,
  },
  {
    code: 338,
    link: null,
    type: "WEAPON",
    name: "",
    view: ``,
  },
  {
    code: 339,
    link: null,
    type: "WEAPON",
    name: "Nightmare Potum",
    view: `Aggro +10%\nFractional Barrier+2%\nMaxHP -5%`,
  },
  {
    code: 340,
    link: null,
    type: "WEAPON",
    name: "Moonlight Potum",
    view: `Attack MP Recovery +3\nCSPD -90%`,
  },
  {
    code: 341,
    link: null,
    type: "WEAPON",
    name: "Miracle Potum",
    view: `MaxHP -10%\nEvasion Recharge +5%`,
  },
  {
    code: 342,
    link: null,
    type: "WEAPON",
    name: "Marchitar",
    view: `Stability +5%\nDodge +15%`,
  },
  {
    code: 343,
    link: null,
    type: "WEAPON",
    name: "Lapin The Necromancer",
    view: `CSPD +100\nMagic Barrier +100\nAdditional Magic +100%`,
  },
  {
    code: 344,
    link: null,
    type: "WEAPON",
    name: "",
    view: ``,
  },
  {
    code: 345,
    link: null,
    type: "WEAPON",
    name: "Imitacia",
    view: `MaxMP +200\nMATK +5%\nGuard Break +10%`,
  },
  {
    code: 346,
    link: null,
    type: "WEAPON",
    name: "Ganglef",
    view: `DEX +2%\nATK +3%\nASPD +1%`,
  },
  {
    code: 347,
    link: null,
    type: "WEAPON",
    name: "Excavated Golem",
    view: `Guard Power +5%\nGuard Rate +5%`,
  },
  {
    code: 348,
    link: null,
    type: "WEAPON",
    name: "Evil Magic Sword",
    view: `Critical Damage +5\nAggro +10%\nAttack MP Recovery +5`,
  },
  {
    code: 349,
    link: null,
    type: "WEAPON",
    name: "Demon's Gate",
    view: `DEX +2%\nMATK +3%\nCSPD +1%`,
  },
  {
    code: 350,
    link: null,
    type: "WEAPON",
    name: "",
    view: ``,
  },
  {
    code: 351,
    link: null,
    type: "WEAPON",
    name: "Death Colon",
    view: `MaxMP -2000\nASPD +1000\nShort Range Damage +10%`,
  },
  {
    code: 352,
    link: null,
    type: "WEAPON",
    name: "Black Knight of Delusion",
    view: `STR +3%\nATK +4%\nDEF -9%\nCritical +2%`,
  },
  {
    code: 353,
    link: null,
    type: "WEAPON",
    name: "Imitator",
    view: `ATK +5%\nAttack MP Recovery +2\nAnticipate +10%`,
  },
  {
    code: 354,
    link: null,
    type: "WEAPON",
    name: "Evil Crystal Beast",
    view: `MATK+4%\nMagic Pierce +3%\nAggro -5%`,
  },
  {
    code: 355,
    link: null,
    type: "ARMOR",
    name: "Altadar",
    view: `Stability +11%\nSTR +6%\nVIT +6%\nWith Light Armor:\nShort Range Damage +11%\nStability -5%\nWith Heavy Armor:\nLong Range Damage +11%\nStability -5%`,
  },
  {
    code: 356,
    link: null,
    type: "ARMOR",
    name: "Aubermight",
    view: `MaxHP +15%\nAggro +30%\nDEF +45`,
  },
  {
    code: 357,
    link: null,
    type: "ARMOR",
    name: "Sibylares",
    view: `ATK +5%\nMATK +5%\nPhysical Pierce +5%\nMagic Pierce +5%\nCritical Rate +15\nMaxMP -100`,
  },
  {
    code: 358,
    link: null,
    type: "ARMOR",
    name: "Dr. Leonardo",
    view: `MATK +2%\nLong Range Damage +6%\nCritical Rate +10%\nMaxHP +5000\nResistansi Status Buruk +5%`,
  },
  {
    code: 359,
    link: null,
    type: "ARMOR",
    name: "",
    view: ``,
  },
  {
    code: 360,
    link: null,
    type: "ARMOR",
    name: "DX Fighter",
    view: `ATK +2%\nShort Range Damage +6%\nAccuracy +10%\nMaxHP +5000\nFractional Barrier +5%`,
  },
  {
    code: 361,
    link: null,
    type: "ARMOR",
    name: "Kruztor",
    view: `MaxHP +5%\nDodge +5%\nKekebalan Fisik +5%\nMagical Resistance +5%\nNeutral Resistance +5%`,
  },
  {
    code: 362,
    link: null,
    type: "ARMOR",
    name: "Doctor Pom Pom",
    view: `Short Range Damage +7%\nCritical Rate +7%\nAilment Resistance +7%`,
  },
  {
    code: 363,
    link: null,
    type: "ARMOR",
    name: "Grim Reaper Scarecrow",
    view: `Long Range Damage +6%\nAggro -15%\nMaxHP -30%`,
  },
  {
    code: 364,
    link: null,
    type: "ARMOR",
    name: "Arachnidemon",
    view: `ATK +8%\nCritical Rate +8\nMaxHP -400\nMaxMP -400\nWith Shield:\nShort Range Damage +4%`,
  },
  {
    code: 365,
    link: null,
    type: "ARMOR",
    name: "",
    view: ``,
  },
  {
    code: 366,
    link: null,
    type: "ARMOR",
    name: "Phantom Wisp",
    view: `Accuracy +20%\nCritical Rate +10\nEvasion Recharge +10%\nDodge Absolut +5%`,
  },
  {
    code: 367,
    link: null,
    type: "ARMOR",
    name: "Gopherga",
    view: `MaxHP +3000\nPhysical Resistance +3%\nMagical Resistance +3%\nShort Range Damage +6%\nAggro +15%`,
  },
  {
    code: 368,
    link: null,
    type: "ARMOR",
    name: "Demonic Quasar",
    view: `MaxMP +1000\nCSPD +300\nMotion Speed +1%`,
  },
  {
    code: 369,
    link: null,
    type: "ARMOR",
    name: "Canemofish",
    view: `Attack MP Recovery +10\nKecepatan Pelindung +10%\nWater resistance +10%`,
  },
  {
    code: 370,
    link: null,
    type: "ARMOR",
    name: "Evil Shadow",
    view: `MaxHP +1500\nMaxMP +300\nMATK +6%\nEvasion Recharge -10%`,
  },
  {
    code: 371,
    link: null,
    type: "ARMOR",
    name: "",
    view: ``,
  },
  {
    code: 372,
    link: null,
    type: "ARMOR",
    name: "Eroded Pilz",
    view: `MaxHP +30%\nPhysical Resistance -10%\nMagical Resistance -10%`,
  },
  {
    code: 373,
    link: null,
    type: "ARMOR",
    name: "Thug Golem",
    view: `Fractional Barrier 10%\nCSPD +15%\nAggro -20%`,
  },
  {
    code: 374,
    link: null,
    type: "ARMOR",
    name: "Iron Empress",
    view: `MaxHP +20%\nPhysical Resistance +10%\nMATK +5%\nMagic Pierce +10%\nCSPD +20%\nMaxMP -300`,
  },
  {
    code: 375,
    link: null,
    type: "ARMOR",
    name: "Noeliel",
    view: `MATK +5%\nCSPD +3%\nAttack MP Recovery +1%`,
  },
  {
    code: 376,
    link: null,
    type: "ARMOR",
    name: "Gagak Penyihir Hebat",
    view: `Stability +4%\nMotion Speed +2%\nAkurasi Absolut +1%\nAilment Resistance -14%`,
  },
  {
    code: 377,
    link: null,
    type: "ARMOR",
    name: "",
    view: ``,
  },
  {
    code: 378,
    link: null,
    type: "ARMOR",
    name: "Goldoon",
    view: `ATK +3%\nMATK +3%\nAccuracy +3%\nAggro -3%`,
  },
  {
    code: 379,
    link: null,
    type: "ARMOR",
    name: "Usakichi",
    view: `MaxMP +100 ATK +1%\nUnsheathe Attack +1%\nNeutral Resistance -1%`,
  },
  {
    code: 380,
    link: null,
    type: "ARMOR",
    name: "Maton Saber",
    view: `STR +3%\nLong Range Damage +4%\nAccuracy +5%\nMaxHP -1000`,
  },
  {
    code: 381,
    link: null,
    type: "ARMOR",
    name: "Tortuga",
    view: `MaxHP +1%\nPhysical Resistance +3%\nGuard Recharge +5%`,
  },
  {
    code: 382,
    link: null,
    type: "ARMOR",
    name: "Jade Raptor",
    view: `MaxMP +300\nCSPD +100\nAttack MP Recovery +1`,
  },
  {
    code: 383,
    link: null,
    type: "ARMOR",
    name: "",
    view: ``,
  },
  {
    code: 384,
    link: null,
    type: "ARMOR",
    name: "Ifrid",
    view: `MaxMP +600\nFractional Barrier +12%`,
  },
  {
    code: 385,
    link: null,
    type: "ARMOR",
    name: "Forestia",
    view: `MATK +1%\nMagical Resistance +3%\nEvasion Recharge +5%`,
  },
  {
    code: 386,
    link: null,
    type: "ARMOR",
    name: "Colon Commander",
    view: `MaxHP +150\nMaxMP +50`,
  },
  {
    code: 387,
    link: null,
    type: "ARMOR",
    name: "Cerberus",
    view: `Physical Pierce +3%\nCritical Damage +3\nUnsheathe Attack +3%`,
  },
  {
    code: 388,
    link: null,
    type: "ARMOR",
    name: "Cerabes",
    view: `MaxHP +1000\nCritical Damage +1`,
  },
  {
    code: 389,
    link: null,
    type: "ARMOR",
    name: "",
    view: ``,
  },
  {
    code: 390,
    link: null,
    type: "ARMOR",
    name: "Boss Roga",
    view: `MaxHP +1000\nWeapon ATK +1%`,
  },
  {
    code: 391,
    link: null,
    type: "ARMOR",
    name: "Arcoiris",
    view: `Natural HP Regen +10%\nMaxHP +10%\nDEF +10%`,
  },
  {
    code: 392,
    link: null,
    type: "SPECIAL",
    name: "Aubergine Dragon Auvio",
    view: `MaxMP +300\nShort Range Damage +4%\nASPD +500\nLong Range Damage -12%\nWith Ninjustu Scroll:\nUnsheathe Attack +5%\nCritical Rate +5`,
  },
  {
    code: 393,
    link: null,
    type: "SPECIAL",
    name: "Vodre",
    view: `Anticipate +5%\nPhysical Resistance +5%\nMagical Resistance +5%\nCritical Damage -150`,
  },
  {
    code: 394,
    link: null,
    type: "SPECIAL",
    name: "Ghost Forest Dark Shaman",
    view: `Magic Pierce +5%\nCSPD +20%\nEvasion Recharge +10%\nMaxMP -300\nWith Shield:\nStability +5%\nATK -10%`,
  },
  {
    code: 395,
    link: null,
    type: "SPECIAL",
    name: "Broker Goblin",
    view: `MaxMP +300\nLong Range Damage +3%\nDEX +3%\nWith Arrow:\nDaya Jarak Jauh +5%\nWith Dagger:\nAdditional Melee +50%\nWith Shield:\nAggro +25%`,
  },
  {
    code: 396,
    link: null,
    type: "SPECIAL",
    name: "",
    view: ``,
  },
  {
    code: 397,
    link: null,
    type: "SPECIAL",
    name: "Dark Captain with B",
    view: `Short Range Damage +3%\nUnsheathe Attack +3%\nMaxMP -150\nFire resistance +10%\nWater resistance +10%\nWind resistance +10%\nEarth resistance +15%`,
  },
  {
    code: 398,
    link: null,
    type: "SPECIAL",
    name: "Stellar Ooze II",
    view: `ATK +5%\nUnsheathe Attack +5%\nPhysical Pierce +5%\nMaxMP +150\nNatural MP Regen +15%\nReduksi DMG (Bowling) +15%\nRevive Time +60%`,
  },
  {
    code: 399,
    link: null,
    type: "SPECIAL",
    name: "Trus",
    view: `Guard Break +10%\nPhysical Pierce +10%\nWith Dual Sword:\nGuard Recharge +25%\nGuard Power +25%`,
  },
  {
    code: 400,
    link: null,
    type: "SPECIAL",
    name: "Wolkissa",
    view: `Attack MP Recovery +5\nVIT +5%\nAilment Resistance +5%\nWith Shield:\nAggro +15%`,
  },
  {
    code: 401,
    link: null,
    type: "SPECIAL",
    name: "Ignitrus",
    view: `MaxHP +1000\nMaxMP +100\nFire resistance +20%\n+5% stronger against Fire`,
  },
  {
    code: 402,
    link: null,
    type: "SPECIAL",
    name: "",
    view: ``,
  },
  {
    code: 403,
    link: null,
    type: "SPECIAL",
    name: "Ruzart",
    view: `Dodge +10\nCritical Rate +10`,
  },
  {
    code: 404,
    link: null,
    type: "SPECIAL",
    name: "Captain Amiya",
    view: `MaxHP +1000\nMaxMP +100\nAttack MP Recovery +10`,
  },
  {
    code: 405,
    link: null,
    type: "SPECIAL",
    name: "Star Wizard",
    view: `MATK +9%\nCSPD +9%\nAnticipate +9%\nWith Staff:\nAggro -9%\nWith Shield:\nAggro +9%`,
  },
  {
    code: 406,
    link: null,
    type: "SPECIAL",
    name: "Dragon Witch",
    view: `Critical Damage +5%\nAttack MP Recovery -100%`,
  },
  {
    code: 407,
    link: null,
    type: "SPECIAL",
    name: "Potumotter",
    view: `MaxMP +400\nAggro -30%\nNeutral Resistance +20%`,
  },
  {
    code: 408,
    link: null,
    type: "SPECIAL",
    name: "",
    view: ``,
  },
  {
    code: 409,
    link: null,
    type: "SPECIAL",
    name: "Volgagon",
    view: `Critical Rate +20%\nASPD +1000\nCSPD -80%`,
  },
  {
    code: 410,
    link: null,
    type: "SPECIAL",
    name: "Frenzy Viola",
    view: `Additional Melee +50%\nATK +1%\nASPD +250`,
  },
  {
    code: 411,
    link: null,
    type: "SPECIAL",
    name: "Grimuckus",
    view: `Additional Magic +50%\nMATK +1%\nASPD +250`,
  },
  {
    code: 412,
    link: null,
    type: "SPECIAL",
    name: "Specter of Death",
    view: `Unsheathe Attack +10%\nAccuracy +15%\nAggro -20%`,
  },
  {
    code: 413,
    link: null,
    type: "SPECIAL",
    name: "Seele Zauga",
    view: `Critical Rate +15\nPhysical Resistance +5%\nMagical Resistance +5%\nKecepatan Item -1.0s`,
  },
  {
    code: 414,
    link: null,
    type: "SPECIAL",
    name: "",
    view: ``,
  },
  {
    code: 415,
    link: null,
    type: "SPECIAL",
    name: "Felien",
    view: `MaxMP +300\nAccuracy +20\nAccuracy +10%\nAkurasi Absolut +5%`,
  },
  {
    code: 416,
    link: null,
    type: "SPECIAL",
    name: "Crystal Titan",
    view: `MaxHP +1000\nMaxHP +10%\nFractional Barrier 10%`,
  },
  {
    code: 417,
    link: null,
    type: "SPECIAL",
    name: "Choiyaki Mentai",
    view: `MaxMP +300\nShort Range Damage +2%\nFire resistance +1%\nMATK -10%\nReduksi DMG (Lantai) -20%`,
  },
  {
    code: 418,
    link: null,
    type: "SPECIAL",
    name: "Venena",
    view: `MaxMP +500\nATK +1%\nMATK +1%\nStability +2%`,
  },
  {
    code: 419,
    link: null,
    type: "SPECIAL",
    name: "Viscum",
    view: `MaxHP +100\nAttack MP Recovery +3`,
  },
  {
    code: 420,
    link: null,
    type: "SPECIAL",
    name: "",
    view: ``,
  },
  {
    code: 421,
    link: null,
    type: "SPECIAL",
    name: "Violacoon",
    view: `MATK -6%\nEvasion Recharge +4%\nAggro +8%`,
  },
  {
    code: 422,
    link: null,
    type: "SPECIAL",
    name: "Stone Mercenary",
    view: `ATK -6%\nGuard Recharge +4%\nAggro +8%`,
  },
  {
    code: 423,
    link: null,
    type: "SPECIAL",
    name: "Shining Gentleman",
    view: `ATK +1%\nMATK +1%\nCritical Damage +1%\nAttack MP Recovery +3`,
  },
  {
    code: 424,
    link: null,
    type: "SPECIAL",
    name: "Ooze",
    view: `ATK +2%\nMATK +2%\nDEF -2%\nMDEF -2%`,
  },
  {
    code: 425,
    link: null,
    type: "SPECIAL",
    name: "Granny",
    view: `MATK +100\nCSPD -1000`,
  },
  {
    code: 426,
    link: null,
    type: "SPECIAL",
    name: "",
    view: ``,
  },
  {
    code: 427,
    link: null,
    type: "SPECIAL",
    name: "Goovua",
    view: `Unsheathe Attack +100\nEvasion Recharge +6%\nAGI +3%`,
  },
  {
    code: 428,
    link: null,
    type: "SPECIAL",
    name: "Golden Potum",
    view: `Untradable
    Base Drop Rate +1%`,
  },
  {
    code: 429,
    link: null,
    type: "SPECIAL",
    name: "Eerie Crystal",
    view: `Attack MP Recovery +5`,
  },
  {
    code: 430,
    link: null,
    type: "SPECIAL",
    name: "Don Yeti",
    view: `ATK +100\nASPD -1000`,
  },
  {
    code: 431,
    link: null,
    type: "SPECIAL",
    name: "Dark Mushroom",
    view: `ATK +1%\nMATK +1%\nMotion Speed +1%`,
  },
  {
    code: 432,
    link: null,
    type: "SPECIAL",
    name: "",
    view: ``,
  },
  {
    code: 433,
    link: null,
    type: "SPECIAL",
    name: "Bexiz",
    view: `MaxMP -100\nAccuracy +15%\nCritical Rate +5\nWeapon ATK +10%`,
  },
  {
    code: 434,
    link: null,
    type: "SPECIAL",
    name: "Titeres",
    view: `Attack MP Recovery +10\nDodge +20\nDodge +10%\nDodge Absolut +5%`,
  },
  {
    code: 435,
    link: null,
    type: "ADDITIONAL",
    name: "Falburrows",
    view: `Long Range Damage +9%\nMaxMP +200\nDodge +10%\nDodge Absolut +5%\nWith Bowgun:\nShort Range Damage +9%`,
  },
  {
    code: 436,
    link: null,
    type: "ADDITIONAL",
    name: "Mage Filecia",
    view: `MATK +9%\nINT +3%\nStability +6%\nWith Staff:\nGuard Break +10%\nWith Magic Device:\nReduksi DMG (Bowling) +20%`,
  },
  {
    code: 437,
    link: null,
    type: "ADDITIONAL",
    name: "Lunadore",
    view: `Base Drop Rate +1%`,
  },
  {
    code: 438,
    link: null,
    type: "ADDITIONAL",
    name: "Purro",
    view: `Base Drop Rate +1%`,
  },
  {
    code: 439,
    link: null,
    type: "ADDITIONAL",
    name: "",
    view: ``,
  },
  {
    code: 440,
    link: null,
    type: "ADDITIONAL",
    name: "Perro",
    view: `Base Drop Rate +1%`,
  },
  {
    code: 441,
    link: null,
    type: "ADDITIONAL",
    name: "Mieli",
    view: `Magic Pierce +10%\nCritical Rate +20%\nASPD +400\nCSPD +400\nMaxHP -20%`,
  },
  {
    code: 442,
    link: null,
    type: "ADDITIONAL",
    name: "Evil Lefina",
    view: `ATK +8%\nPhysical Pierce +10%\nCritical Rate +12\nMATK -4%\nPhysical Resistance -20%\nWith Heavy Armor:\nKekebalan Fisik +24%`,
  },
  {
    code: 443,
    link: null,
    type: "ADDITIONAL",
    name: "Eidenliebe",
    view: `MaxHP +12%\nMagic Pierce +10%\nAggro -15%`,
  },
  {
    code: 444,
    link: null,
    type: "ADDITIONAL",
    name: "Junior Dragon Zyvio",
    view: `ATK +5%\nCritical Rate +15\nMaxMP +100\nGuard Break 5%`,
  },
  {
    code: 445,
    link: null,
    type: "ADDITIONAL",
    name: "",
    view: ``,
  },
  {
    code: 446,
    link: null,
    type: "ADDITIONAL",
    name: "Ox King",
    view: `Aggro -20%`,
  },
  {
    code: 447,
    link: null,
    type: "ADDITIONAL",
    name: "Bonivio",
    view: `Base Drop Rate +1%`,
  },
  {
    code: 448,
    link: null,
    type: "ADDITIONAL",
    name: "Lord of Nezim",
    view: `MaxHP +3000\nVIT +2%\nCritical Rate +10\nWith Knuckle:\n Short Range Damage +3%`,
  },
  {
    code: 449,
    link: null,
    type: "ADDITIONAL",
    name: "Adaro",
    view: `MATK +6%\nCritical Damage +6\nMaxHP +1000\nWith Heavy Armor:\nAggro +10%`,
  },
  {
    code: 450,
    link: null,
    type: "ADDITIONAL",
    name: "Mercy",
    view: `Critical Rate +15\nAggro -15%`,
  },
  {
    code: 451,
    link: null,
    type: "ADDITIONAL",
    name: "",
    view: ``,
  },
  {
    code: 452,
    link: null,
    type: "ADDITIONAL",
    name: "Omochi",
    view: `Base Drop Rate +1%`,
  },
  {
    code: 453,
    link: null,
    type: "ADDITIONAL",
    name: "Yashiro Azuki's Dad",
    view: `ATK +4%\nShort Range Damage +3%\nASPD +20%\nAggro -10%`,
  },
  {
    code: 454,
    link: null,
    type: "ADDITIONAL",
    name: "Narumi Hina",
    view: `MATK +4%\nLong Range Damage +3%\nCSPD +20%\nAggro -10%`,
  },
  {
    code: 455,
    link: null,
    type: "ADDITIONAL",
    name: "Goldenia",
    view: `MaxHP +2000\nFractional Barrier 10%\nMaxMP -300`,
  },
  {
    code: 456,
    link: null,
    type: "ADDITIONAL",
    name: "Handmade Cookie",
    view: `Physical Pierce +10%\nMaxHP +12%\nAggro -15%`,
  },
  {
    code: 457,
    link: null,
    type: "ADDITIONAL",
    name: "",
    view: ``,
  },
  {
    code: 458,
    link: null,
    type: "ADDITIONAL",
    name: "Celeng Mini Merah Putih",
    view: `Base Drop Rate +1%`,
  },
  {
    code: 459,
    link: null,
    type: "ADDITIONAL",
    name: "Altoblepas",
    view: `Critical Damage +4\nDEX +1%\nAccuracy -20%`,
  },
  {
    code: 460,
    link: null,
    type: "ADDITIONAL",
    name: "Golden Iconos",
    view: `MaxHP +1000\nReduksi DMG (Terjang) +10%`,
  },
  {
    code: 461,
    link: null,
    type: "ADDITIONAL",
    name: "Gespenst II",
    view: `Critical Rate +10\nAccuracy +30\nMaxMP +200\nCSPD +200`,
  },
  {
    code: 462,
    link: null,
    type: "ADDITIONAL",
    name: "Yashiro Azuki's Mom",
    view: `Critical Rate +10\nPhysical Resistance +5%\nMagical Resistance +5%\nReduksi DMG (Peluru) +10%`,
  },
  {
    code: 463,
    link: null,
    type: "ADDITIONAL",
    name: "",
    view: ``,
  },
  {
    code: 464,
    link: null,
    type: "ADDITIONAL",
    name: "Warmonger",
    view: `Critical Rate +6\nCritical Damage +2`,
  },
  {
    code: 465,
    link: null,
    type: "ADDITIONAL",
    name: "Twilight Dragon",
    view: `Short Range Damage +4%\nLong Range Damage +4%\nUnsheathe Attack +4%`,
  },
  {
    code: 466,
    link: null,
    type: "ADDITIONAL",
    name: "Sunlight Potum",
    view: `ASPD +300\nCSPD +300\nMaxHP -5%\nMaxMP -75`,
  },
  {
    code: 467,
    link: null,
    type: "ADDITIONAL",
    name: "Seltirios",
    view: `MaxMP -150\nCSPD +300`,
  },
  {
    code: 468,
    link: null,
    type: "ADDITIONAL",
    name: "Pumpking",
    view: `Critical Damage +1\nFire resistance +2%\nAttack MP Recovery +3`,
  },
  {
    code: 469,
    link: null,
    type: "ADDITIONAL",
    name: "",
    view: ``,
  },
  {
    code: 470,
    link: null,
    type: "ADDITIONAL",
    name: "Grylle",
    view: `MaxHP +500\nDEF +5%\nGuard Power +5%`,
  },
  {
    code: 471,
    link: null,
    type: "ADDITIONAL",
    name: "Grass Dragon Yelb",
    view: `ATK +3%\nASPD +50%\nLong Range Damage -10%`,
  },
  {
    code: 472,
    link: null,
    type: "ADDITIONAL",
    name: "Grand Pojo",
    view: `Base Drop Rate +1%`,
  },
  {
    code: 473,
    link: null,
    type: "ADDITIONAL",
    name: "Golden Skeleton",
    view: `MaxHP -10%\nASPD +300`,
  },
  {
    code: 474,
    link: null,
    type: "ADDITIONAL",
    name: "Giant Boar",
    view: `MaxHP +50\nMaxMP +50\nShort Range Damage +1%`,
  },
  {
    code: 475,
    link: null,
    type: "ADDITIONAL",
    name: "",
    view: ``,
  },
  {
    code: 476,
    link: null,
    type: "ADDITIONAL",
    name: "Dusk Machina",
    view: `MaxHP +20%\nAggro +10%\nLong Range Damage -10%`,
  },
  {
    code: 477,
    link: null,
    type: "ADDITIONAL",
    name: "Corroded Knight Captain",
    view: `DEF +100 MDEF +100\nPhysical Barrier +500\nMagic Barrier +500`,
  },
  {
    code: 478,
    link: null,
    type: "ADDITIONAL",
    name: "Chocolate Ooze",
    view: `CSPD +500\nMaxHP -10%\nMaxMP +200`,
  },
  {
    code: 479,
    link: null,
    type: "ADDITIONAL",
    name: "Candela",
    view: `MaxHP +10%\nMaxMP -200\nASPD +500`,
  },
  {
    code: 480,
    link: null,
    type: "ADDITIONAL",
    name: "Ancient Empress",
    view: `MATK +3%\nCSPD +50%\nShort Range Damage -10%`,
  },
  {
    code: 481,
    link: null,
    type: "NORMAL",
    name: "Radibat",
    view: `Stability 4%\nAccuracy 4%\nCritical Rate 4%`,
  },
  {
    code: 482,
    link: 323,
    type: "UPGRADE",
    name: "Diark",
    view: `MATK +8%\nMagic Pierce +20%\nCast Speed -16%`,
  },
  {
    code: 483,
    link: 234,
    type: "UPGRADE",
    name: "Gegner",
    view: `MATK +10%\nINT +6%\nCast Speed +40%\nAttack MP Recovery +10%`,
  },
  {
    code: 484,
    link: null,
    type: "SPECIAL",
    name: "Scream Shadow",
    view: `MaxMP +300\nCritical Rate +20%\nCast Speed +1000\nDEF -40%`,
  },
  {
    code: 485,
    link: 26,
    type: "UPGRADE",
    name: "Mighty Gerumi",
    view: `MaxHP +400\nMaxMP +200\nStability +2%\nAccuracy +2%\nCritical Rate +4`,
  },
  {
    code: 486,
    link: null,
    type: "SPECIAL",
    name: "Giant Pelulu",
    view: `Short Range Damage +10%\nMaxHP +30%\nCritical Rate +50%\nMaxMP -100\nWith Light Armor:\nPhysical Pierce -10%`,
  },
  {
    code: 487,
    link: null,
    type: "ARMOR",
    name: "Bangrudom",
    view: `ATK +10%\nMATK +10%\nAttack Speed +10%\nCast Speed +10%\nMaxHP -20%\nWith Shield:\nDEX +5%\nWith Light Armor:\nMagic Pierce +5%`,
  },
  {
    code: 488,
    link: 285,
    type: "UPGRADE",
    name: "limacina",
    view: `Ailment Resistance +5%\nPhysical Resistance +5%\nMagic Resistance +5%`,
  },
  {
    code: 489,
    link: 221,
    type: "UPGRADE",
    name: "Vatudo",
    view: `MATK +10%\nMagic Pierce +7%\nAggro -11%\nMDEF -30%`,
  },
  {
    code: 490,
    link: 459,
    type: "UPGRADE",
    name: "Jiva",
    view: `MATK +8%\nCritical Damage +6\nDEX +3%\nAccuracy -20%`,
  },
  {
    code: 491,
    link: 215,
    type: "UPGRADE",
    name: "Raging Dragon Bovinari",
    view: `Short Range Damage +7%\nAttack MP Recovery +15\nPhysical Barrier +3000\nMagic Barrier +3000`,
  },
  {
    code: 492,
    link: 316,
    type: "UPGRADE",
    name: "Doridodi",
    view: `Accuracy +17%\nLong Range Damage +10%\nMaxHP -25%`,
  },
  {
    code: 493,
    link: 240,
    type: "UPGRADE",
    name: "Humida",
    view: `MaxMP +700\nATK +4%\nMATK +4%\nStability +4%`,
  },
  {
    code: 494,
    link: 231,
    type: "UPGRADE",
    name: "Torexesa",
    view: `ATK +10%\nMATK +10%\nAttack MP Recovery +4\nMaxMP -200`,
  },
  {
    code: 495,
    link : 172,
    type: "UPGRADE",
    name: "Breeta",
    view: `Attack MP Recovery +15%\nMaxHP +5000\nStability +2%`,
  },
  {
    code: 496,
    link : null,
    type: "NORMAL",
    name: "VIT+8",
    view: `VIT +8`,
  },
  {
    code: 497,
    link : 216,
    type: "UPGRADE",
    name: "Meteora",
    view: `Unsheathe Attack +9%\nPhysical Pierce +5%\nCritical Damage +7`,
  },
  {
    code: 498,
    link : null,
    type: "ARMOR",
    name: "Mulgoon's Hand",
    view: `Short Range Damage +6%\nLong Range Damage +4%\nAccuracy +5%\nMaxHP +10000\nMaxMP -100`,
  },
  {
    code: 499,
    link : null,
    type: "ADDITIONAL",
    name: "Jibril",
    view: `Short Range Damage +3%\nLong Range Damage +5%\nMaxMP +100\nCritical Rate +8\nAnticipate +1%\nNatural MP Regen +2\nNatural MP Regen +4%`,
  },
  {
    code: 500,
    link : 499,
    type: "UPGRADE",
    name: "Jibril II",
    view: `Short Range Damage +6%\nLong Range Damage +8%\nMaxMP +100\nCritical Rate +12\nAnticipate +2%\nNatural MP Regen +4\nNatural MP Regen +8%`,
  },
  {
    code: 501,
    link : 500,
    type: "UPGRADE",
    name: "Jibril III",
    view: `Short Range Damage +9%\nLong Range Damage +11%\nMaxMP +100\nCritical Rate +16\nAnticipate +3%\nNatural MP Regen +6\nNatural MP Regen +12%`,
  },
  {
    code: 502,
    link : 407,
    type: "UPGRADE",
    name: "Potumotter II",
    view: `MaxMP +400\nnMotion Speed +1%\nAggro -30%\nNeutral Resistance +25%`,
  },
  {
    code: 503,
    link : 180,
    type: "UPGRADE",
    name: "Hero Potum IV",
    view: `MaxHP +13%\nFractional Barrier +16%\nAccuracy +19%\nAggro +22%`,
  },
  {
    code: 504,
    link : 198,
    type: "UPGRADE",
    name: "Deformis",
    view: `ATK +11%\nAttack MP Recovery +8\nAnticipate 14%\nMaxMP -200`,
  },
  {
    code: 505,
    link : 239,
    type: "UPGRADE",
    name: "Wiltileaf",
    view: `ATK +9%\nCritical Damage +12\nMotion Speed 0%\nMagical Resistance -15%`,
  },
    {
    code: 506,
    link : 410,
    type: "UPGRADE",
    name: "Frenzy Viola G",
    view: `Additional Melee 75%\nAdditional Magic 75%\nWith One-Handed Sword:\nAdditional Melee 25%\nWith Magic Tools:\nAdditional Magic 25%`,
  },
    {
    code: 507,
    link : 131,
    type: "UPGRADE",
    name: "Great Kijimu",
    view: `MaxHP +700\nMaxMP +300\nPhysical Piercer +1%\nMagic Piercer +1%`,
  },
    {
    code: 508,
    link : 215,
    type: "UPGRADE",
    name: "Queen Rosemee",
    view: `Long Range Damage +5%\nAttack MP Recovery +5\nMagic Piercer +5%\nCritical Rate +5%`,
  },
    {
    code: 509,
    link : 372,
    type: "UPGRADE",
    name: "Tulin Max",
    view: `MaxHP -30%\nPhysical Resistance +10%\nMagic Resistance +10%\nCritical Rate +10`,
  },
  {
    code: 510,
    link : 372,
    type: "SPECIAL",
    name: "Zeagrystal",
    view: `Short Range Damage +2%\nStability +2%\nPhysical Resistance +3%\nMagical Resistance +3%\nWith Shield:\nAilment Resistance +5%`,
  },
  {
    code: 511,
    link : 372,
    type: "UPGRADE",
    name: "Abyssal Crystal Monster",
    view: `Short Range Damage +4%\nStability +4%\nPhysical Resistance +6%\nMagical Resistance +6%\nWith Shield:\nAilment Resistance +5%`,
  },
  {
    code: 512,
    link: null,
    type: "ADDITIONAL",
    name: "Castilia",
    view: `Short Range Damage +12%\nLong Range Damage +6%\nAccuracy +10%\nWith Magic Tools:\nMotion Speed +5%\nWith Ninjutsu Scroll:\nMagic Pierce +10%`
  }
]
