[
  {
    code: 1,
    link: null,
    name: "Akurasi+16",
    type: "NORMAL",
    view: `Akurasi +16`,
  },
  {
    code: 2,
    link: null,
    name: "Dodge+16",
    type: "NORMAL",
    view: `Dodge +16`,
  },
  {
    code: 3,
    link: null,
    name: "ASPD+140",
    type: "NORMAL",
    view: `ASPD +140`,
  },
  {
    code: 4,
    link: null,
    name: "CSPD+140",
    type: "NORMAL",
    view: `CSPD +140`,
  },
  {
    code: 5,
    link: null,
    name: "DEX+7",
    type: "NORMAL",
    view: `DEX +7`,
  },
  {
    code: 6,
    link: null,
    name: "INT+7",
    type: "NORMAL",
    view: `INT +7`,
  },
  {
    code: 7,
    link: null,
    name: "STR+7",
    type: "NORMAL",
    view: `STR +7`,
  },
  {
    code: 8,
    link: null,
    name: "AGI+7",
    type: "NORMAL",
    view: `AGI +7`,
  },
  {
    code: 9,
    link: null,
    name: "Kalajengkel",
    type: "NORMAL",
    view: `Critical Rate +10%\nStability +2%\nDaya Jarak Dekat -1%`,
  },
  {
    code: 10,
    link: null,
    name: "Akurasi+14",
    type: "NORMAL",
    view: `Akurasi +14`,
  },
  {
    code: 12,
    link: null,
    name: "Dodge+14",
    type: "NORMAL",
    view: `Dodge +14`,
  },
  {
    code: 13,
    link: null,
    name: "VIT+14",
    type: "NORMAL",
    view: `VIT +14`,
  },
  {
    code: 14,
    link: null,
    name: "Gurita Raksasa",
    type: "NORMAL",
    view: `Attack MP Recovery +5\nCritical Rate +10\nASPD +150\nCSPD +250\nKebal Api -4%\nResistensi Status Buruk -2%\nReduksi DMG (Bowling) -1%`,
  },
  {
    code: 15,
    link: null,
    name: "HP+700",
    type: "NORMAL",
    view: `HP +700`,
  },
  {
    code: 16,
    link: null,
    name: "CSPD+120",
    type: "NORMAL",
    view: `CSPD +120`,
  },
  {
    code: 17,
    link: null,
    name: "INT+6",
    type: "NORMAL",
    view: `INT +6`,
  },
  {
    code: 18,
    link: null,
    name: "MP+300",
    type: "NORMAL",
    view: `CSPD +120`,
  },
  {
    code: 19,
    link: null,
    name: "STR+6",
    type: "NORMAL",
    view: `STR +6`,
  },
  {
    code: 20,
    link: null,
    name: "AGI+6",
    type: "NORMAL",
    view: `AGI +6`,
  },
  {
    code: 21,
    link: null,
    name: "VIT+6",
    type: "NORMAL",
    view: `VIT +6`,
  },
  {
    code: 22,
    link: null,
    name: "Gravicep",
    type: "NORMAL",
    view: `Daya Jarak Dekat +7%\nAkurasi +3%\nMaxMP +200\nCritical Rate -5\nMaxHP -100`,
  },
  {
    code: 23,
    link: null,
    name: "DODGE+12",
    type: "NORMAL",
    view: `DODGE +12`,
  },
  {
    code: 24,
    link: null,
    name: "ASPD+120",
    type: "NORMAL",
    view: `ASPD +120`,
  },
  {
    code: 25,
    link: null,
    name: "Shawle",
    type: "NORMAL",
    view: `Antisipasi 5%\nGuard Break 5%\nAkurasi +20%\nAggro +10%`,
  },
  {
    code: 26,
    link: null,
    name: "Gerumi",
    type: "NORMAL",
    view: `MaxHP +200\nMaxMP +100`,
  },
  {
    code: 27,
    link: null,
    name: "DEX+6",
    type: "NORMAL",
    view: `DEX +6`,
  },
  {
    code: 28,
    link: null,
    name: "Akurasi+12",
    type: "NORMAL",
    view: `Akurasi +12`,
  },
  {
    code: 29,
    link: null,
    name: "Critical Rate+5",
    type: "NORMAL",
    view: `Critical Rate +5`,
  },
  {
    code: 30,
    link: null,
    name: "STR+5",
    type: "NORMAL",
    view: `STR+5`,
  },
  {
    code: 31,
    link: null,
    name: "Carbuncle",
    type: "NORMAL",
    view: `MaxHP +1000\nRefleks +10%\nDodge -10%`,
  },
  {
    code: 32,
    link: null,
    name: "VIT+5",
    type: "NORMAL",
    view: `VIT +5`,
  },
  {
    code: 33,
    link: null,
    name: "Lynx Mithurna",
    type: "NORMAL",
    view: `Daya Jarak Dekat +3%\nStability +3%\nEvasion Recharge +3%\nDaya Jarak Jauh -9%`,
  },
  {
    code: 34,
    link: null,
    name: "HP+500",
    type: "NORMAL",
    view: `HP +500`,
  },
  {
    code: 35,
    link: null,
    name: "Yashiro Azuki",
    type: "NORMAL",
    view: `EXP +1%\nMaxHP +200\nMaxMP +100`,
  },
  {
    code: 36,
    link: null,
    name: "P. Avatar",
    type: "NORMAL",
    view: `Untradable
    EXP +1%\nKebal Api +1%\nKebal Angin +%\nKebal Air +1%\nKebal Bumi +1%\nKebal Cahaya +1%\nKebal Gelap -1%`,
  },
  {
    code: 37,
    link: null,
    name: "Bos Petapa Kadal",
    type: "NORMAL",
    view: `Critical Damage +3\nReduksi DMG (Sekitar Pemain) -3%\nReduksi DMG (Sekitar Musuh) -3%`,
  },
  {
    code: 38,
    link: null,
    name: "INT+5",
    type: "NORMAL",
    view: `INT +5`,
  },
  {
    code: 39,
    link: null,
    name: "DEX+5",
    type: "NORMAL",
    view: `DEX +5`,
  },
  {
    code: 40,
    link: null,
    name: "INT+4",
    type: "NORMAL",
    view: `INT +4`,
  },
  {
    code: 41,
    link: null,
    name: "Critical Rate+4",
    type: "NORMAL",
    view: `Critical Rate +4`,
  },
  {
    code: 42,
    link: null,
    name: "DEX+4",
    type: "NORMAL",
    view: `DEX +4`,
  },
  {
    code: 43,
    link: null,
    name: "Dodge+8",
    type: "NORMAL",
    view: `Dodge +8`,
  },
  {
    code: 44,
    link: null,
    type: "NORMAL",
    name: "Akurasi+10",
    view: `Akurasi +10`,
  },
  {
    code: 45,
    link: null,
    type: "NORMAL",
    name: "ASPD+100",
    view: `ASPD +100`,
  },
  {
    code: 46,
    link: null,
    type: "NORMAL",
    name: "CSPD+100",
    view: `CSPD +100`,
  },
  {
    code: 47,
    link: null,
    type: "NORMAL",
    name: "Dodge+10",
    view: `Dodge +10`,
  },
  {
    code: 48,
    link: null,
    type: "NORMAL",
    name: "",
    view: ``,
  },
  {
    code: 49,
    link: null,
    type: "NORMAL",
    name: "AGI+5",
    view: `AGI +5`,
  },
  {
    code: 50,
    link: null,
    type: "NORMAL",
    name: "Odelon Machina",
    view: `Dodge -5%\nEvasion Recharge -5%\nSerangan Menghunus +10%`,
  },
  {
    code: 51,
    link: null,
    type: "NORMAL",
    name: "Ksatriaja",
    view: `ATK +1%\nCritical Damage +1\nSTR +1%\nAkurasi -10%\nCritical Rate -10%`,
  },
  {
    code: 52,
    link: null,
    type: "NORMAL",
    name: "VIT+4",
    view: `VIT +4`,
  },
  {
    code: 53,
    link: null,
    type: "NORMAL",
    name: "VIT+3",
    view: `VIT +3`,
  },
  {
    code: 54,
    link: null,
    type: "NORMAL",
    name: "",
    view: ``,
  },
  {
    code: 55,
    link: null,
    type: "NORMAL",
    name: "VIT+2",
    view: `VIT +2`,
  },
  {
    code: 56,
    link: null,
    type: "NORMAL",
    name: "HP+600",
    view: `MaxHP +600`,
  },
  {
    code: 57,
    link: null,
    type: "NORMAL",
    name: "Super Night Mushroom",
    view: `MaxHP +500\nDaya Jarak Jauh +1%\nDaya Jarak Dekat +1%`,
  },
  {
    code: 58,
    link: null,
    type: "NORMAL",
    name: "STR+4",
    view: `STR +4`,
  },
  {
    code: 59,
    link: null,
    type: "NORMAL",
    name: "STR+3",
    view: `STR +3`,
  },
  {
    code: 60,
    link: null,
    type: "NORMAL",
    name: "",
    view: ``,
  },
  {
    code: 61,
    link: null,
    type: "NORMAL",
    name: "STR+2",
    view: `STR +2`,
  },
  {
    code: 62,
    link: null,
    type: "NORMAL",
    name: "STR+1",
    view: `STR +1`,
  },
  {
    code: 63,
    link: null,
    type: "NORMAL",
    name: "Silver Roar",
    view: `MaxHP -8%\nAttack MP Recovery +4`,
  },
  {
    code: 64,
    link: null,
    type: "NORMAL",
    name: "Scrader",
    view: `Natural MP Regen -10%\nMaxHP +300\nMATK +3%\nKekebalan Fisik -20%\nDaya Jarak Jauh +2%`,
  },
  {
    code: 65,
    link: null,
    type: "NORMAL",
    name: "Golem Kuno",
    view: `MaxHP +200\nMDEF +5%\nKekebalan Sihir +1%`,
  },
  {
    code: 66,
    link: null,
    type: "NORMAL",
    name: "",
    view: ``,
  },
  {
    code: 67,
    link: null,
    type: "NORMAL",
    name: "Nurethoth",
    view: `ATK +3%\nMATK +3%\nASPD -150\nCSPD -150`,
  },
  {
    code: 68,
    link: null,
    type: "NORMAL",
    name: "MP+50",
    view: `MaxMP +50`,
  },
  {
    code: 69,
    link: null,
    type: "NORMAL",
    name: "MP+200",
    view: `MaxMP +200`,
  },
  {
    code: 70,
    link: null,
    type: "NORMAL",
    name: "MP+150",
    view: `MaxMP +150`,
  },
  {
    code: 71,
    link: null,
    type: "NORMAL",
    name: "MP+100",
    view: `MaxMP +100`,
  },
  {
    code: 72,
    link: null,
    type: "NORMAL",
    name: "",
    view: ``,
  },
  {
    code: 73,
    link: null,
    type: "NORMAL",
    name: "Mochelo",
    view: `MaxHP +5%\nCSPD +10%`,
  },
  {
    code: 74,
    link: null,
    type: "NORMAL",
    name: "Minotaur",
    view: `ASPD +10%\nMaxHP +5%`,
  },
  {
    code: 75,
    link: null,
    type: "NORMAL",
    name: "Metal Stinger",
    view: `ATK +2%\nKekebalan Sihir-10%\nCritical Damage +3\nKecepatan Aksi -1%`,
  },
  {
    code: 76,
    link: null,
    type: "NORMAL",
    name: "Megiston",
    view: `STR +1\nINT +1\nVIT +1\nAGI +1\nDEX +1\nMaxHP +100\nMaxMP +50`,
  },
  {
    code: 77,
    link: null,
    type: "NORMAL",
    name: "Mauez",
    view: `MaxMP +150\nAkurasi -4%\nCritical Rate +2`,
  },
  {
    code: 78,
    link: null,
    type: "NORMAL",
    name: "",
    view: ``,
  },
  {
    code: 79,
    link: null,
    type: "NORMAL",
    name: "Pendekar Bertopeng",
    view: `MaxHP -3%\nAkurasi -3\nATK +1%\nMATK +1%\nAttack MP Recovery +2`,
  },
  {
    code: 80,
    link: null,
    type: "NORMAL",
    name: "Potum Raja",
    view: `MaxHP +10%\nKekebalan Fisik -5%\nKekebalan Sihir -5%`,
  },
  {
    code: 81,
    link: null,
    type: "NORMAL",
    name: "Inzanio",
    view: `Guard Recharge +1%\nAttack MP Recovery -1\nWeapon ATK +10\nPelindung Fraksional+3%`,
  },
  {
    code: 82,
    link: null,
    type: "NORMAL",
    name: "INT+3",
    view: `INT +3`,
  },
  {
    code: 83,
    link: null,
    type: "NORMAL",
    name: "INT+2",
    view: `INT +2`,
  },
  {
    code: 84,
    link: null,
    type: "NORMAL",
    name: "",
    view: ``,
  },
  {
    code: 85,
    link: null,
    type: "NORMAL",
    name: "INT+1",
    view: `INT +1`,
  },
  {
    code: 86,
    link: null,
    type: "NORMAL",
    name: "HP+400",
    view: `MaxHP +400`,
  },
  {
    code: 87,
    link: null,
    type: "NORMAL",
    name: "HP+300",
    view: `MaxHP +300`,
  },
  {
    code: 88,
    link: null,
    type: "NORMAL",
    name: "HP+200",
    view: `MaxHP +200`,
  },
  {
    code: 89,
    link: null,
    type: "NORMAL",
    name: "HP+100",
    view: `MaxHP +100`,
  },
  {
    code: 90,
    link: null,
    type: "NORMAL",
    name: "",
    view: ``,
  },
  {
    code: 91,
    link: null,
    type: "NORMAL",
    name: "Gespenst",
    view: `MaxMP +150\nATK -1%\nMATK -1%`,
  },
  {
    code: 92,
    link: null,
    type: "NORMAL",
    name: "Anjing Hutan",
    view: `Dodge +6\nEvasion Recharge +2%`,
  },
  {
    code: 93,
    link: null,
    type: "NORMAL",
    name: "Flare Volg",
    view: `STR +3\nKekebalan Sihir -4%\nDaya Jarak Jauh +2%`,
  },
  {
    code: 94,
    link: null,
    type: "NORMAL",
    name: "Dodge+6",
    view: `Dodge +6`,
  },
  {
    code: 95,
    link: null,
    type: "NORMAL",
    name: "Dodge+4",
    view: `Dodge +4`,
  },
  {
    code: 96,
    link: null,
    type: "NORMAL",
    name: "",
    view: ``,
  },
  {
    code: 97,
    link: null,
    type: "NORMAL",
    name: "Dodge+2",
    view: `Dodge +2`,
  },
  {
    code: 98,
    link: null,
    type: "NORMAL",
    name: "DEX+3",
    view: `DEX +3`,
  },
  {
    code: 99,
    link: null,
    type: "NORMAL",
    name: "DEX+2",
    view: `DEX +2`,
  },
  {
    code: 100,
    link: null,
    type: "NORMAL",
    name: "DEX+1",
    view: `DEX +1`,
  },
  {
    code: 101,
    link: null,
    type: "NORMAL",
    name: "CSPD+80",
    view: `CSPD +80`,
  },
  {
    code: 102,
    link: null,
    type: "NORMAL",
    name: "",
    view: ``,
  },
  {
    code: 103,
    link: null,
    type: "NORMAL",
    name: "CSPD+60",
    view: `CSPD +60`,
  },
  {
    code: 104,
    link: null,
    type: "NORMAL",
    name: "CSPD+40",
    view: `CSPD +40`,
  },
  {
    code: 105,
    link: null,
    type: "NORMAL",
    name: "CSPD+20",
    view: `CSPD +20`,
  },
  {
    code: 106,
    link: null,
    type: "NORMAL",
    name: "Critical Rate+3",
    view: `Critical Rate +3`,
  },
  {
    code: 107,
    link: null,
    type: "NORMAL",
    name: "Critical Rate+2",
    view: `Critical Rate +2`,
  },
  {
    code: 108,
    link: null,
    type: "NORMAL",
    name: "",
    view: ``,
  },
  {
    code: 109,
    link: null,
    type: "NORMAL",
    name: "Critical Rate+1",
    view: `Critical Rate +1`,
  },
  {
    code: 110,
    link: null,
    type: "NORMAL",
    name: "Crimsosch",
    view: `AGI +3\nDodge +3\nCritical Rate -9\nEvasion Recharge +3%`,
  },
  {
    code: 111,
    link: null,
    type: "NORMAL",
    name: "Caspy",
    view: `Resistensi Status Buruk -6%\nGuard Power +2%\nGuard Recharge +2%\nEvasion Recharge +2%`,
  },
  {
    code: 112,
    link: null,
    type: "NORMAL",
    name: "Goblin Bos",
    view: `ATK +1%\nAkurasi -4\nCritical Rate +2%`,
  },
  {
    code: 113,
    link: null,
    type: "NORMAL",
    name: "Coryn Besar",
    view: `Kekebalan Fisik+1%\nKekebalan Sihir +1%\nResistensi Status Buruk +1%`,
  },
  {
    code: 114,
    link: null,
    type: "NORMAL",
    name: "",
    view: ``,
  },
  {
    code: 115,
    link: null,
    type: "NORMAL",
    name: "B.B. Goblin",
    view: `ATK +2%\nCritical Rate -1\nAggro +5%`,
  },
  {
    code: 116,
    link: null,
    type: "NORMAL",
    name: "Astol",
    view: `DEF -10%\nKekebalan Sihir +1%\nEvasion Recharge +3%`,
  },
  {
    code: 117,
    link: null,
    type: "NORMAL",
    name: "ASPD+80",
    view: `ASPD +80`,
  },
  {
    code: 118,
    link: null,
    type: "NORMAL",
    name: "ASPD+60",
    view: `ASPD +60`,
  },
  {
    code: 119,
    link: null,
    type: "NORMAL",
    name: "ASPD+40",
    view: `ASPD +40`,
  },
  {
    code: 120,
    link: null,
    type: "NORMAL",
    name: "",
    view: ``,
  },
  {
    code: 121,
    link: null,
    type: "NORMAL",
    name: "ASPD+20",
    view: `ASPD +20`,
  },
  {
    code: 122,
    link: null,
    type: "NORMAL",
    name: "Aranea",
    view: `MaxHP +400\nMaxMP +200\nAggro +1%`,
  },
  {
    code: 123,
    link: null,
    type: "NORMAL",
    name: "AGI+4",
    view: `AGI +4`,
  },
  {
    code: 124,
    link: null,
    type: "NORMAL",
    name: "AGI+3",
    view: `AGI +3`,
  },
  {
    code: 125,
    link: null,
    type: "NORMAL",
    name: "AGI+2",
    view: `AGI +2`,
  },
  {
    code: 126,
    link: null,
    type: "NORMAL",
    name: "",
    view: ``,
  },
  {
    code: 127,
    link: null,
    type: "NORMAL",
    name: "AGI+1",
    view: `AGI +1`,
  },
  {
    code: 128,
    link: null,
    type: "NORMAL",
    name: "Akurasi+8",
    view: `Akurasi +8`,
  },
  {
    code: 129,
    link: null,
    type: "NORMAL",
    name: "Akurasi+6",
    view: `Akurasi +6`,
  },
  {
    code: 130,
    link: null,
    type: "NORMAL",
    name: "Akurasi+4",
    view: `Akurasi +4`,
  },
  {
    code: 131,
    link: null,
    type: "NORMAL",
    name: "Bos Colon",
    view: `MaxHP +70\nMaxMP +30`,
  },
  {
    code: 132,
    link: null,
    type: "NORMAL",
    name: "",
    view: ``,
  },
  {
    code: 133,
    link: null,
    type: "NORMAL",
    name: "Akurasi +2",
    view: `Akurasi +2`,
  },
  {
    code: 134,
    link: null,
    type: "NORMAL",
    name: "Naga Beringas Decel",
    view: `ATK +1%\nMATK +1%\nMaxMP -50`,
  },
  {
    code: 135,
    link: null,
    type: "NORMAL",
    name: "MP+250",
    view: `MaxMP +250`,
  },

  {
    code: 136,
    link: 229,
    type: "UPGRADE",
    name: "Don Profundo",
    view: `ATK +10%\nSTR +7%\nCritical Rate +8%\nDEF -27%`,
  },
  {
    code: 137,
    link: 286,
    type: "UPGRADE",
    name: "Capo Profundo",
    view: `Guard Recharge +8%\nKekebalan Fisik +12%\nMaxHP +16%`,
  },
  {
    code: 138,
    link: 470,
    type: "UPGRADE",
    name: "Fantica",
    view: `MaxHP +500\nGuard Power +15%\nDEF +10%`,
  },
  {
    code: 139,
    link: 22,
    type: "UPGRADE",
    name: "Naga Abu Merah Rudis",
    view: `Daya Jarak Dekat +9%\nAkurasi +5%\nMaxMP +200\nCritical Rate -7\nMaxHP -300`,
  },
  {
    code: 140,
    link: null,
    type: "UPGRADE",
    name: "",
    view: ``,
  },
  {
    code: 141,
    link: 364,
    type: "UPGRADE",
    name: "Zapo",
    view: `ATK +10%\nCritical Rate +10\nMaxHP -400\nMaxMP -400\nDengan Perisai:\nDaya Jarak Dekat +5%\nSTR +1%`,
  },
  {
    code: 142,
    link: 33,
    type: "UPGRADE",
    name: "Kuffania",
    view: `Daya Jarak Dekat +4%\nStability +4%\nEvasion Recharge +4%\nDaya Jarak Jauh -12%`,
  },
  {
    code: 143,
    link: 208,
    type: "UPGRADE",
    name: "Eripmav",
    view: `Attack MP Recovery +18\nKebal Api +12%\nCritical Damage +6`,
  },
  {
    code: 144,
    link: 358,
    type: "UPGRADE",
    name: "Dr. Leonardo II",
    view: `MATK +3%\nDaya Jarak Jauh +6%\nCritical Rate +20%\nMaxHP +6000\nResistansi Status Buruk +5%`,
  },
  {
    code: 145,
    link: 360,
    type: "UPGRADE",
    name: "DX Fighter II",
    view: `ATK +3%\nDaya Jarak Dekat +6%\nAkurasi +15%\nMaxHP +6000\nPelindung Fraksional +5%`,
  },
  {
    code: 146,
    link: null,
    type: "UPGRADE",
    name: "",
    view: ``,
  },
  {
    code: 147,
    link: 409,
    type: "UPGRADE",
    name: "Etoise",
    view: `Critical Rate +40%\nkecepatan Serangan +1100\nKecepatan Aksi +5%\nCSPD -70%`,
  },
  {
    code: 148,
    link: 287,
    type: "UPGRADE",
    name: "Dominaredor",
    view: `ATK +8%\nMATK +8%\nASPD +20%\nReduksi DMG (Lantai) +20%`,
  },
  {
    code: 149,
    link: 241,
    type: "UPGRADE",
    name: "Lilicarolla",
    view: `Serangan Menghunus +18%\nDodge -5%\nMaxMP -100`,
  },
  {
    code: 150,
    link: 225,
    type: "UPGRADE",
    name: "Baavgai",
    view: `MaxHP +7000\nCritical Damage +7\nDaya Jarak Dekat +5%`,
  },
  {
    code: 151,
    link: 93,
    type: "UPGRADE",
    name: "Charugon",
    view: `STR +6\nDaya Jarak Dekat +3%\nDaya Jarak Jauh +6%\nKekebalan Sihir -12%`,
  },
  {
    code: 152,
    link: null,
    type: "UPGRADE",
    name: "",
    view: ``,
  },
  {
    code: 153,
    link: 247,
    type: "UPGRADE",
    name: "Naga Trompet Reguita",
    view: `ATK +10%\nMATK +10%\nNatural HP Regen -12%\nNatural MP Regen -12%`,
  },
  {
    code: 154,
    link: 361,
    type: "UPGRADE",
    name: "Kruztor II",
    view: `MaxHP +7%\nDodge +7%\nKekebalan Fisik +7%\nKekebalan Sihir +7%\nKebal Normal +7%`,
  },
  {
    code: 155,
    link: 204,
    type: "UPGRADE",
    name: "Walican",
    view: `MaxHP +6000\nWeapon ATK +6%`,
  },
  {
    code: 156,
    link: 37,
    type: "UPGRADE",
    name: "Orictoceras",
    view: `Critical Damage +9\nReduksi DMG (Sekitar Pemain) -3%\nReduksi DMG (Sekitar Musuh) -3%`,
  },
  {
    code: 157,
    link: 246,
    type: "UPGRADE",
    name: "Sicanokami",
    view: `Daya Jarak Dekat +5%\nAttack MP Recovery +20\nAkurasi +50\nDengan Tombak:\nDaya Jarak Jauh +5%`,
  },
  {
    code: 158,
    link: null,
    type: "UPGRADE",
    name: "",
    view: ``,
  },
  {
    code: 159,
    link: 478,
    type: "UPGRADE",
    name: "Chocolate Ooze II",
    view: `MaxHP -15%\nMaxMP +300\nCSPD +600`,
  },
  {
    code: 160,
    link: 268,
    type: "UPGRADE",
    name: "Amargon",
    view: `Kecepatan Serang +800\nMaxHP +30%\nMaxMP +300`,
  },
  {
    code: 161,
    link: 162,
    type: "UPGRADE",
    name: "Sang Juara Megiston V",
    view: `MaxHP +1800\nCritical Rate +23\nKebal Api +6%\nKebal Air +6%\nKebal Angin +3%\nKebal Bumi +3%\nKebal Cahaya +3%`,
  },
  {
    code: 162,
    link: 163,
    type: "UPGRADE",
    name: "Sang Juara Megiston IV",
    view: `MaxHP +1600\nCritical Rate +20\nKebal Api +6%\nKebal Air +3%\nKebal Angin +3%\nKebal Cahaya +3%`,
  },
  {
    code: 163,
    link: 165,
    type: "UPGRADE",
    name: "Sang Juara Megiston III",
    view: `MaxHP +1400\nCritical Rate +18\nKebal Api +3%\nKebal Angin +3%\nKebal Cahaya +3%`,
  },
  {
    code: 164,
    link: null,
    type: "UPGRADE",
    name: "",
    view: ``,
  },
  {
    code: 165,
    link: 328,
    type: "UPGRADE",
    name: "Sang Juara Megiston II",
    view: `MaxHP +1200\nCritical Rate +16\nKebal Api +3%\nKebal Cahaya +3%`,
  },
  {
    code: 166,
    link: 213,
    type: "UPGRADE",
    name: "Zega VII",
    view: `MaxHP +1000\nAttack MP Recovery +9\nKekebalan Sihir +8%\nKebal Air +7%`,
  },
  {
    code: 167,
    link: 386,
    type: "UPGRADE",
    name: "Goleps",
    view: `MaxMP +250\nMaxHP +750`,
  },
  {
    code: 168,
    link: 322,
    type: "UPGRADE",
    name: "Cakar Kucing Kissatpam",
    view: `ATK +10%\nAGI +4%\nResistensi Status Buruk +2%\nAttack MP Recovery +2\nMaxHP -12%`,
  },
  {
    code: 169,
    link: 171,
    type: "UPGRADE",
    name: "Gem Mas",
    view: `MaxHP +3000\nReduksi DMG (Terjang) +10%\nReduksi DMG (Linear) +10%\nReduksi DMG (Sekitar Pemain) +10%`,
  },
  {
    code: 170,
    link: null,
    type: "UPGRADE",
    name: "",
    view: ``,
  },
  {
    code: 171,
    link: 460,
    type: "UPGRADE",
    name: "Kodok Riang",
    view: `MaxHP +2000\nReduksi DMG (Terjang) +10%\nReduksi DMG (Linear) +10%`,
  },
  {
    code: 172,
    link: 250,
    type: "UPGRADE",
    name: "Crysmort",
    view: `Attack MP Recovery +11\nMaxHP +3000\nStability +1%`,
  },
  {
    code: 173,
    link: 279,
    type: "UPGRADE",
    name: "Roda Kelana Neo",
    view: `Daya Jarak Jauh -16%\nMATK +5%\nCSPD +75%`,
  },
  {
    code: 174,
    link: 67,
    type: "UPGRADE",
    name: "Nuthoreth",
    view: `ATK +2%\nMATK +2%\nASPD +150\nCSPD +150`,
  },
  {
    code: 175,
    link: 468,
    type: "UPGRADE",
    name: "Jeila",
    view: `Attack MP Recovery +6\nKebal Api +4%\nCritical Damage +2`,
  },
  {
    code: 176,
    link: null,
    type: "UPGRADE",
    name: "",
    view: ``,
  },
  {
    code: 177,
    link: 370,
    type: "UPGRADE",
    name: "Velly Hitam",
    view: `MaxHP +3000\nMaxMP +400\nMATK +9%\nEvasion Recharge -20%`,
  },
  {
    code: 178,
    link: 323,
    type: "UPGRADE",
    name: "Kadal Bunga",
    view: `Stability +5%\nPeneterasi Sihir +20%\nAggro -15%`,
  },
  {
    code: 179,
    link: 325,
    type: "UPGRADE",
    name: "Pedrio",
    view: `ATK +10%\nMATK +10%\nReduksi DMG (Bowling) +20%\nReduksi DMG (Peluru) +20%\nAggro -40%`,
  },
  {
    code: 180,
    link: 226,
    type: "UPGRADE",
    name: "Potum Pahlawan III",
    view: `MaxHP +12%\nPelindung Fraksional +14%\nAkurasi +16%\nAggro +18%`,
  },
  {
    code: 181,
    link: 329,
    type: "UPGRADE",
    name: "Pomie Chan II",
    view: `ATK +9%\nAGI +7%\nAggro -15%\nDengan Sarung Tinju:\nDodge Absolut +5%\n`,
  },
  {
    code: 182,
    link: null,
    type: "UPGRADE",
    name: "",
    view: ``,
  },
  {
    code: 183,
    link: 465,
    type: "UPGRADE",
    name: "Baphomela",
    view: `Daya Jarak Dekat +6%\nDaya Jarak Jauh +6%\nSerangan menghunus +6%`,
  },
  {
    code: 184,
    link: 238,
    type: "UPGRADE",
    name: "Naga Jahat Fazzino",
    view: `MATK +9%\nDEX +7%\nCSPD +5%`,
  },
  {
    code: 185,
    link: 372,
    type: "UPGRADE",
    name: "Filrocas",
    view: `MaxHP +60%\nKekebalan Sihir -7%\nKekebalan Fisik -7%\nDengan Sarung Tinju:\nAggro +15%\nDengan Pedang 1 Tangan:\nAggro +15%`,
  },
  {
    code: 186,
    link: 477,
    type: "UPGRADE",
    name: "Exdocus",
    view: `DEF +150\nMDEF +150\nPelindung Fisik +1500\nPelindung Sihir +1500`,
  },
  {
    code: 187,
    link: 294,
    type: "UPGRADE",
    name: "Brassozard",
    view: `STR +3%\nATK +3%\nAkurasi -10%\nCritical Rate -10%\nCritical Damage +3`,
  },
  {
    code: 188,
    link: null,
    type: "UPGRADE",
    name: "",
    view: ``,
  },
  {
    code: 189,
    link: 265,
    type: "UPGRADE",
    name: "Naga Membara Igneus",
    view: `AGI +3%\nCritical Rate +15\nCritical Damage +8`,
  },
  {
    code: 190,
    link: 373,
    type: "UPGRADE",
    name: "Naga Langkisau",
    view: `CSPD +20%\nAggro -30%\nPelindung Fraksional +10%`,
  },
  {
    code: 191,
    link: 289,
    type: "UPGRADE",
    name: "Golem Satpam",
    view: `ATK +9%\nMATK +9%\nASPD -225\nCSPD -225`,
  },
  {
    code: 192,
    link: 274,
    type: "UPGRADE",
    name: "Gordel",
    view: `MaxMP +800\nPelindung Fraksional +17%\nCritical Rate +3`,
  },
  {
    code: 193,
    link: 264,
    type: "UPGRADE",
    name: "Oculasignio",
    view: `MaxMP +300\nMATK +9%\nGuard Break +13%`,
  },
  {
    code: 194,
    link: null,
    type: "UPGRADE",
    name: "",
    view: ``,
  },
  {
    code: 195,
    link: 385,
    type: "UPGRADE",
    name: "Glaucius",
    view: `Evasion Recharge +15%\nKekebalan Sihir +6%\nMATK +6%\nDengan Zirah Ringan:\nMATK UP (AGI25%\n)`,
  },
  {
    code: 196,
    link: 243,
    type: "UPGRADE",
    name: "Naga Penyamar Mimyugon",
    view: `ATK +9%\nDEX +7%\nASPD +5%`,
  },
  {
    code: 197,
    link: 443,
    type: "UPGRADE",
    name: "Garnache",
    view: `MaxHP +18%\nMATK +3%\nPeneterasi Sihir +10%\nAggro -15%`,
  },
  {
    code: 198,
    link: 269,
    type: "UPGRADE",
    name: "Velum",
    view: `ATK +9%\nAttack MP Recovery +6\nAntisipasi 13%\nMaxMP -100`,
  },
  {
    code: 199,
    link: 122,
    type: "UPGRADE",
    name: "Blazingur",
    view: `MaxHP +600\nMaxMP +300\nAggro +2%`,
  },
  {
    code: 200,
    link: null,
    type: "UPGRADE",
    name: "",
    view: ``,
  },
  {
    code: 201,
    link: 293,
    type: "UPGRADE",
    name: "Vlam si Naga Api",
    view: `MaxMP +400\nDaya Jarak Dekat +6%\nPhysical Pierce +7%`,
  },
  {
    code: 202,
    link: 481,
    type: "UPGRADE",
    name: "Melancia",
    view: `Stability +5%\nAkurasi +5%\nCritical Rate +5%`,
  },
  {
    code: 203,
    link: 183,
    type: "UPGRADE",
    name: "Bayangan Biru Tafakur",
    view: `Daya Jarak Dekat +8%\nDaya Jarak Jauh +8%\nSerangan Menghunus +8%\nMaxMP -150`,
  },
  {
    code: 204,
    link: 252,
    type: "UPGRADE",
    name: "Ferzen si Naga Batu",
    view: `MaxHP +5000\nWeaponATK +5%`,
  },
  {
    code: 205,
    link: 271,
    type: "UPGRADE",
    name: "Naga Milisi Turba",
    view: `Critical Rate +11\nWeapon Attack +14%\nAkurasi +17%\nMaxMP -200`,
  },
  {
    code: 206,
    link: null,
    type: "UPGRADE",
    name: "",
    view: ``,
  },
  {
    code: 207,
    link: 279,
    type: "UPGRADE",
    name: "Gordo",
    view: `Daya Jarak Jauh -15%\nATK +7%\nASPD +80%`,
  },
  {
    code: 208,
    link: 259,
    type: "UPGRADE",
    name: "Neewollah",
    view: `Attack MP Recovery +15\nKebal Api +10%\nCritical Damage +5`,
  },
  {
    code: 209,
    link: 301,
    type: "UPGRADE",
    name: "Bullamius",
    view: `MP +250\nATK +3%\nMATK +3%`,
  },
  {
    code: 210,
    link: 431,
    type: "UPGRADE",
    name: "Teertocrit",
    view: `ATK +6%\nMATK +6%\nKecepatan Aksi +2%`,
  },
  {
    code: 211,
    link: 280,
    type: "UPGRADE",
    name: "Usamochi",
    view: `MaxMP +300\nATK +6%\nSerangan Menghunus +6%\nKebal Normal -10%`,
  },
  {
    code: 212,
    link: null,
    type: "UPGRADE",
    name: "",
    view: ``,
  },
  {
    code: 213,
    link: 237,
    type: "UPGRADE",
    name: "Zega VI",
    view: `MaxHP +900\nAttack MP Recovery +8\nKekebalan Sihir +7%\nKebal Air +6%`,
  },
  {
    code: 214,
    link: 367,
    type: "UPGRADE",
    name: "Yuveria",
    view: `MaxMP+300\nKekebalan Fisik +3%\nKekebalan Sihir +3%\nDaya Jarak Dekat +6%\nAggro -15%`,
  },
  {
    code: 215,
    link: 333,
    type: "UPGRADE",
    name: "Penyihir Besi Bercakar",
    view: `Daya Jarak Dekat +5%\nAttack MP Recovery +10\nPelindung Fisik +2000\nPelindung Sihir +2000`,
  },
  {
    code: 216,
    link: 258,
    type: "UPGRADE",
    name: "Gemma",
    view: `Serangan Menghunus +7%\nPhysical Pierce +5%\nCritical Damage +6`,
  },
  {
    code: 217,
    link: 74,
    type: "UPGRADE",
    name: "Rhinosaurus",
    view: `MaxHP +10%\nASPD +15%\nATK +5%`,
  },
  {
    code: 218,
    link: null,
    type: "UPGRADE",
    name: "",
    view: ``,
  },
  {
    code: 219,
    link: 446,
    type: "UPGRADE",
    name: "Paduka Raja Kerbau",
    view: `Daya Jarak Dekat +8%\nAkurasi +40\nMaxMP +200\nMaxHP -20%`,
  },
  {
    code: 220,
    link: 446,
    type: "UPGRADE",
    name: "Pillow Kitagawa",
    view: `Serangan Menghunus +8%\nCritical Rate +4\nMaxHP +2000\nRevive Time +20%`,
  },
  {
    code: 221,
    link: 282,
    type: "UPGRADE",
    name: "Irestida",
    view: `MATK +8%\nPeneterasi Sihir +6%\nAggro -9%\nMDEF -24%`,
  },
  {
    code: 222,
    link: 476,
    type: "UPGRADE",
    name: "Trocostida",
    view: `MaxHP +20%\nCritical Rate +5\nAggro +15%\nDaya Jarak Jauh -10%`,
  },
  {
    code: 223,
    link: 456,
    type: "UPGRADE",
    name: "Alfenix",
    view: `ATK +3%\nPhysical Pierce +10%\nMaxHP +18%\nAggro -15%`,
  },
  {
    code: 224,
    link: null,
    type: "UPGRADE",
    name: "",
    view: ``,
  },
  {
    code: 225,
    link: 267,
    type: "UPGRADE",
    name: "Sakura Merah Jelita",
    view: `MaxHP +4000\nCritical Damage +4\nDaya Jarak Dekat +2%`,
  },
  {
    code: 226,
    link: 331,
    type: "UPGRADE",
    name: "Potum Pahlawan II",
    view: `MaxHP +11%\nPelindung Fraksional +12%\nAkurasi +13%\nAggro +14%`,
  },
  {
    code: 227,
    link: 228,
    type: "UPGRADE",
    name: "✝Raja Kegelapan✝",
    view: `ATK +5%\nDaya Jarak Dekat +3%\nASPD +20%\nAggro -10%`,
  },
  {
    code: 228,
    link: 454,
    type: "UPGRADE",
    name: "Ibu Yashiro Azuki II",
    view: `MATK +5%\nDaya Jarak Jauh +3%\nCSPD +20%\nAggro -10%`,
  },
  {
    code: 229,
    link: 292,
    type: "UPGRADE",
    name: "Hexter",
    view: `ATK +8%\nSTR +6%\nCritical Rate +6%\nDEF -21%`,
  },
  {
    code: 230,
    link: null,
    type: "UPGRADE",
    name: "",
    view: ``,
  },
  {
    code: 231,
    link: 263,
    type: "UPGRADE",
    name: "Bayangan Hitam",
    view: `ATK +8%\nMATK +8%\nAttack MP Recovery+3\nMaxMP -150`,
  },
  {
    code: 232,
    link: 443,
    type: "UPGRADE",
    name: "Gernache",
    view: `MATK +3%\nPeneterasi Sihir +10%\nMaxHP +18%\nAggro -15%`,
  },
  {
    code: 233,
    link: 461,
    type: "UPGRADE",
    name: "Stellar Ooze",
    view: `Critical Rate +20\nAkurasi +60\nMaxMP +300\nCSPD +600`,
  },
  {
    code: 234,
    link: 273,
    type: "UPGRADE",
    name: "Kucing Yule",
    view: `MATK +7%\nINT +3%\nCSPD +35%\nAttack MP Recovery +10%`,
  },
  {
    code: 235,
    link: 423,
    type: "UPGRADE",
    name: "Roh Orang Mati",
    view: `Attack MP Recovery +4\nATK +2%\nMATK +2%\nCritical Damage +2%`,
  },
  {
    code: 236,
    link: null,
    type: "UPGRADE",
    name: "",
    view: ``,
  },
  {
    code: 237,
    link: 257,
    type: "UPGRADE",
    name: "Zega V",
    view: `MaxHP +800\nAttack MP Recovery +7\nKekebalan Sihir +6%\nKebal Air +5%`,
  },
  {
    code: 238,
    link: 295,
    type: "UPGRADE",
    name: "Pisteus",
    view: `MATK +7%\nDEX +5%\nCSPD +3%`,
  },
  {
    code: 239,
    link: 291,
    type: "UPGRADE",
    name: "Ageladanios",
    view: `ATK +6%\nCritical Damage +8\nKecepatan Aksi -1%\nKekebalan Sihir -15%`,
  },
  {
    code: 240,
    link: 418,
    type: "UPGRADE",
    name: "Venena II",
    view: `MaxMP +600\nATK +2%\nMATK +2%\nStability +3%`,
  },
  {
    code: 241,
    link: 50,
    type: "UPGRADE",
    name: "Pret",
    view: `Serangan Menghunus +12%\nDodge -5%\nEvasion Recharge -3%\nMaxMP -50`,
  },
  {
    code: 242,
    link: null,
    type: "UPGRADE",
    name: "",
    view: ``,
  },
  {
    code: 243,
    link: 298,
    type: "UPGRADE",
    name: "Vulture",
    view: `ATK +7%\nDEX +5%\nASPD +3%`,
  },
  {
    code: 244,
    link: 421,
    type: "UPGRADE",
    name: "Ketua Bandit Gurun",
    view: `Evasion Recharge +8%\nAggro +16%\nMATK -5%`,
  },
  {
    code: 245,
    link: 467,
    type: "UPGRADE",
    name: "Tardigrademon",
    view: `CSPD +450\nMaxMP -200`,
  },
  {
    code: 246,
    link: 300,
    type: "UPGRADE",
    name: "Patissia",
    view: `Attack MP Recovery +15\nAkurasi +25`,
  },
  {
    code: 247,
    link: 335,
    type: "UPGRADE",
    name: "Repthon",
    view: `ATK +6%\nMATK +6%\nNatural MP Regen -10%\nNatural HP Regen -10%`,
  },
  {
    code: 248,
    link: null,
    type: "UPGRADE",
    name: "",
    view: ``,
  },
  {
    code: 249,
    link: 368,
    type: "UPGRADE",
    name: "Mata Jahanam",
    view: `MaxHP +1000\nASPD +300\nTumble Unavailable`,
  },
  {
    code: 250,
    link: 299,
    type: "UPGRADE",
    name: "Amalgam",
    view: `Attack MP Recovery +9\nMaxHP +2000`,
  },
  {
    code: 251,
    link: 348,
    type: "UPGRADE",
    name: "Kristal Berlumur Darah",
    view: `Attack MP Recovery +7\nCritical Damage +6\nAggro +10%`,
  },
  {
    code: 252,
    link: 277,
    type: "UPGRADE",
    name: "Roga Safir",
    view: `MaxHP +4000\nWeapon ATK +4%`,
  },
  {
    code: 253,
    link: 474,
    type: "UPGRADE",
    name: "Mega Alpoca",
    view: `Daya Jarak Dekat +6%\nMaxHP +300\nMaxMP +300`,
  },
  {
    code: 254,
    link: null,
    type: "UPGRADE",
    name: "",
    view: ``,
  },
  {
    code: 255,
    link: 336,
    type: "UPGRADE",
    name: "Zega II",
    view: `MaxHP +500\nAttack MP Recovery +4\nKekebalan Sihir +3%\nKebal Air +2%`,
  },
  {
    code: 256,
    link: 255,
    type: "UPGRADE",
    name: "Zega III",
    view: `MaxHP +600\nAttack MP Recovery +5\nKekebalan Sihir +4%\nKebal Air +3%`,
  },
  {
    code: 257,
    link: 256,
    type: "UPGRADE",
    name: "Zega IV",
    view: `MaxHP +700\nAttack MP Recovery +6\nKekebalan Sihir +5%\nKebal Air +4%`,
  },
  {
    code: 258,
    link: 387,
    type: "UPGRADE",
    name: "Pyxtica",
    view: `Serangan Menghunus +4%\nPhysical Pierce +4%\nCritical Damage +4`,
  },
  {
    code: 259,
    link: 276,
    type: "UPGRADE",
    name: "Zarth",
    view: `Attack MP Recovery +12\nKebal Api +8%\nCritical Damage +4`,
  },
  {
    code: 260,
    link: null,
    type: "UPGRADE",
    name: "",
    view: ``,
  },
  {
    code: 261,
    link: 330,
    type: "UPGRADE",
    name: "Mbah Dukun Usasama II",
    view: `MATK +7%\nCSPD +14%\nKecepatan Aksi +3%\nMaxHP -15%\nAttack MP Recovery -30%`,
  },
  {
    code: 262,
    link: 346,
    type: "UPGRADE",
    name: "Kepiting Bulan Besar",
    view: `ATK +6%\nVIT +4%\nKecepatan Aksi +1%`,
  },
  {
    code: 263,
    link: 297,
    type: "UPGRADE",
    name: "Tuscog",
    view: `ATK +6%\nMATK +6%\nAttack MP Recovery +2\nMaxMP -100`,
  },
  {
    code: 264,
    link: 345,
    type: "UPGRADE",
    name: "Finstern si Naga Kegelapan",
    view: `MATK +7%\nMaxMP +300\nGuard Break +12%`,
  },
  {
    code: 265,
    link: 303,
    type: "UPGRADE",
    name: "Piton Raja",
    view: `Critical Rate +10\nCritical Damage +4`,
  },
  {
    code: 266,
    link: null,
    type: "UPGRADE",
    name: "",
    view: ``,
  },
  {
    code: 267,
    link: 388,
    type: "UPGRADE",
    name: "Mimesia",
    view: `MaxHP +2000\nCritical Damage +2`,
  },
  {
    code: 268,
    link: 479,
    type: "UPGRADE",
    name: "Candela II",
    view: `MaxHP +20%\nMaxMP -250\nASPD +600`,
  },
  {
    code: 269,
    link: 353,
    type: "UPGRADE",
    name: "Mardula",
    view: `ATK +7%\nAttack MP Recovery +4\nAntisipasi +12%`,
  },
  {
    code: 270,
    link: 343,
    type: "UPGRADE",
    name: "Momok Gelembung",
    view: `Tambahan Sihir +125%\nCSPD +200\nPelindung Sihir +200`,
  },
  {
    code: 271,
    link: 433,
    type: "UPGRADE",
    name: "Zelbuse",
    view: `Critical Rate +8\nWeapon ATK +12%\nAkurasi +16%\nMaxMP -150`,
  },
  {
    code: 272,
    link: null,
    type: "UPGRADE",
    name: "",
    view: ``,
  },
  {
    code: 273,
    link: 375,
    type: "UPGRADE",
    name: "Noeliel si Patung Es Suci",
    view: `MATK +5%\nCSPD +30%\nAttack MP Recovery +10%`,
  },
  {
    code: 274,
    link: 384,
    type: "UPGRADE",
    name: "Mama Fluck",
    view: `MaxMP +700\nPelindung Fraksional +15%`,
  },
  {
    code: 275,
    link: 80,
    type: "UPGRADE",
    name: "Potum Platina",
    view: `MaxHP +20%\nKekebalan Fisik -10%\nKekebalan Sihir -10%`,
  },
  {
    code: 276,
    link: 175,
    type: "UPGRADE",
    name: "Zoe",
    view: `Attack MP Recovery +9\nKebal Api +6%\nCritical Damage +3`,
  },
  {
    code: 277,
    link: 305,
    type: "UPGRADE",
    name: "Ornlarf",
    view: `MaxHP +3000\nWeapon ATK +3%`,
  },
  {
    code: 278,
    link: null,
    type: "UPGRADE",
    name: "",
    view: ``,
  },
  {
    code: 279,
    link: 471,
    type: "UPGRADE",
    name: "Roda Kelana",
    view: `ATK +5%\nASPD +75%\nDaya Jarak Jauh -14%`,
  },
  {
    code: 280,
    link: 379,
    type: "UPGRADE",
    name: "Usami",
    view: `MaxMP +300\nATK +3%\nSerangan Menghunus +3%\nKebal Normal -10%`,
  },
  {
    code: 281,
    link: 473,
    type: "UPGRADE",
    name: "Solopy",
    view: `ASPD +450\nMaxHP -15%`,
  },
  {
    code: 282,
    link: 354,
    type: "UPGRADE",
    name: "Shampy",
    view: `MATK +6%\nPeneterasi Sihir +5%\nAggro -7%\nMDEF -18%`,
  },
  {
    code: 283,
    link: 110,
    type: "UPGRADE",
    name: "Amoeba Machina",
    view: `AGI +6\nDodge +5\nEvasion Recharge +4%\nCritical Rate -6`,
  },
  {
    code: 284,
    link: null,
    type: "UPGRADE",
    name: "",
    view: ``,
  },
  {
    code: 285,
    link: 113,
    type: "UPGRADE",
    name: "Seraph Machina",
    view: `Resistensi Status Buruk +3%\nKekebalan Fisik +3%\nKekebalan Sihir +3%`,
  },
  {
    code: 286,
    link: 381,
    type: "UPGRADE",
    name: "Daddy Finpen",
    view: `MaxHP +6%\nGuard Rate +6%\nKekebalan Fisik +6%`,
  },
  {
    code: 287,
    link: 424,
    type: "UPGRADE",
    name: "Lalvada",
    view: `ATK +4%\nMATK +4%\nDEF -4%\nMDEF-4%`,
  },
  {
    code: 288,
    link: 382,
    type: "UPGRADE",
    name: "Jamur Super Mampus",
    view: `MaxMP +400\nCSPD +200\nAttack MP Recovery +3`,
  },
  {
    code: 289,
    link: 67,
    type: "UPGRADE",
    name: "Guignol",
    view: `ATK +5%\nMATK +5%\nASPD -175\nCSPD -175`,
  },
  {
    code: 290,
    link: null,
    type: "UPGRADE",
    name: "",
    view: ``,
  },
  {
    code: 291,
    link: 75,
    type: "UPGRADE",
    name: "Kapten Lyark Spesialis",
    view: `ATK +3%\nCritical Damage +4\nKebal Sihir -15%\nKecepatan Aksi -2%`,
  },
  {
    code: 292,
    link: 352,
    type: "UPGRADE",
    name: "Gwaimol",
    view: `ATK +6%\nSTR +5%\nCritical Rate +4%\nDEF -15%`,
  },
  {
    code: 293,
    link: 337,
    type: "UPGRADE",
    name: "Machina Ultima",
    view: `MaxMP +400\nPhysical Pierce +4%\nDaya Jarak Dekat +4%`,
  },
  {
    code: 294,
    link: 51,
    type: "UPGRADE",
    name: "Volotur",
    view: `ATK +2%\nSTR +2%\nCritical Damage +2\nAkurasi -10%\nCritical Rate -10%`,
  },
  {
    code: 295,
    link: 349,
    type: "UPGRADE",
    name: "Mozto Machina",
    view: `DEX +4%\nMATK +6%\nCSPD +2%`,
  },
  {
    code: 296,
    link: null,
    type: "UPGRADE",
    name: "",
    view: ``,
  },
  {
    code: 297,
    link: 134,
    type: "UPGRADE",
    name: "York",
    view: `ATK +4%\nMATK +4%\nAttack MP Recovery +1\nMaxMP -75`,
  },
  {
    code: 298,
    link: 346,
    type: "UPGRADE",
    name: "Tyrant Machina",
    view: `ATK +6%\nDEX +4%\nASPD +2%`,
  },
  {
    code: 299,
    link: 419,
    type: "UPGRADE",
    name: "Deniala",
    view: `MaxHP +1000\nAttack MP Recovery +6`,
  },
  {
    code: 300,
    link: 429,
    type: "UPGRADE",
    name: "Tapir",
    view: `Attack MP Recovery +10`,
  },
  {
    code: 301,
    link: 91,
    type: "UPGRADE",
    name: "Salamander",
    view: `MaxMP +200\nATK +1%\nMATK +1%`,
  },
  {
    code: 302,
    link: null,
    type: "UPGRADE",
    name: "",
    view: ``,
  },
  {
    code: 303,
    link: 464,
    type: "UPGRADE",
    name: "Proto Leon",
    view: `Critical Rate +8\nCritical Damage +3`,
  },
  {
    code: 304,
    link: 422,
    type: "UPGRADE",
    name: "Memecoleous",
    view: `ATK -4%\nGuard Recharge +5%\nAggro +12%`,
  },
  {
    code: 305,
    link: 390,
    type: "UPGRADE",
    name: "Iconos",
    view: `MaxHP +2000\nWeapon ATK +2%`,
  },
  {
    code: 306,
    link: 347,
    type: "UPGRADE",
    name: "Builder Golem",
    view: `Guard Power +7%\nGuard Recharge +7%`,
  },
  {
    code: 307,
    link: 480,
    type: "UPGRADE",
    name: "Ratu Kuno II",
    view: `MATK +5%\nCSPD +30%\nDaya Jarak Dekat -20%`,
  },
  {
    code: 308,
    link: null,
    type: "UPGRADE",
    name: "",
    view: ``,
  },
  {
    code: 309,
    link: 449,
    type: "UPGRADE",
    name: "Monster Dasar Laut",
    view: `MATK+8%\nCritical Damage +8\nMaxHP +1000\nDengan Zirah Berat:\nAggro +20%`,
  },
  {
    code: 310,
    link: null,
    type: "WEAPON",
    name: "Sinar Rembulan Purba",
    view: `ATK +10%\nMATK +10%\nMaxHP +10%\nAntisipasi +10%\nGuard Break +10%\nMaxMP -200`,
  },
  {
    code: 311,
    link: null,
    type: "WEAPON",
    name: "Crysta Terkutuk",
    view: `ATK +5%\nMATK +5%\nStability +5%\nKecepatan Aksi +5%\nRecoil +20%`,
  },
  {
    code: 312,
    link: null,
    type: "WEAPON",
    name: "Putri Natal Berbaju Hitam",
    view: `ATK +9%\nMATK +9%\nSTR +3%\nINT +3%\nDaya Jarak Jauh -6%\nTumble Unavailable\nDengan Perisai:\nAggro -50%`,
  },
  {
    code: 313,
    link: null,
    type: "WEAPON",
    name: "Semangat Musim Panas",
    view: `MaxHP +15%\nCritical Rate +20\nKebal Api +25%\nRecoil +3,00%`,
  },
  {
    code: 314,
    link: null,
    type: "WEAPON",
    name: "",
    view: ``,
  },
  {
    code: 315,
    link: null,
    type: "WEAPON",
    name: "Serigala Merah Mata Satu",
    view: `Daya Jarak Dekat +8%\nAntisipasi +4%\nKekebalan Fisik -16%\nKekebalan Sihir -8%\nDengan Belati:\nCritical Damage +1%\nDengan Pedang Ganda :\nAggro -20%`,
  },
  {
    code: 316,
    link: null,
    type: "WEAPON",
    name: "Arbogazella",
    view: `Daya Jarak Jauh +7%\nAkurasi +14%\nMaxHP -28%`,
  },
  {
    code: 317,
    link: null,
    type: "WEAPON",
    name: "Dango Iblis",
    view: `ATK +4%\nPhysical Pierce +20%\nAggro -10%\nResistansi Status Buruk -15%\nMaxMP -200`,
  },
  {
    code: 318,
    link: null,
    type: "WEAPON",
    name: "Tikus Kecil Ajaib",
    view: `Daya Jarak Jauh +4%\nSerangan Menghunus +4%\nAggro -20%\nDengan Tongkat:MATK +6%`,
  },
  {
    code: 319,
    link: null,
    type: "WEAPON",
    name: "Jeandoux",
    view: `Critical Damage +7\nSTR +3%\nAggro -10%`,
  },
  {
    code: 320,
    link: null,
    type: "WEAPON",
    name: "",
    view: ``,
  },
  {
    code: 321,
    link: null,
    type: "WEAPON",
    name: "Kuzto",
    view: `MATK +7%\nCritical Rate +7\nAggro -7%`,
  },
  {
    code: 322,
    link: null,
    type: "WEAPON",
    name: "Metasrigala",
    view: `ATK +7%\nAGI +4%\nAttack MP Recovery +1\nMaxHP -12%`,
  },
  {
    code: 323,
    link: null,
    type: "WEAPON",
    name: "Armasite",
    view: `MATK +5%\nPeneterasi Sihir +20%\nCSPD -15%`,
  },
  {
    code: 324,
    link: null,
    type: "WEAPON",
    name: "Badut Tukang Sandiwara",
    view: `Akurasi +10%\nCritical Rate +10\nASPD +200\nCSPD +200`,
  },
  {
    code: 325,
    link: null,
    type: "WEAPON",
    name: "Pedang Neo Maton",
    view: `ATK +7%\nMATK +7%\nReduksi DMG (Bowling) +14%\nReduksi DMG (Peluru) +14%\nAggro -28%`,
  },
  {
    code: 326,
    link: null,
    type: "WEAPON",
    name: "",
    view: ``,
  },
  {
    code: 327,
    link: null,
    type: "WEAPON",
    name: "Grecia",
    view: `ATK +6%\nMATK +6%\nPhysical Pierce +3%\nPeneterasi Sihir +3%`,
  },
  {
    code: 328,
    link: null,
    type: "WEAPON",
    name: "Sang Juara Megiston",
    view: `MaxHP +1000\nCritical Rate +15\nKebal Api +3%`,
  },
  {
    code: 329,
    link: null,
    type: "WEAPON",
    name: "Pomie Chan",
    view: `ATK +5%\nAGI +5%\nAggro -5%\nDengan Sarung Tinju:\nDodge Absolut +5%`,
  },
  {
    code: 330,
    link: null,
    type: "WEAPON",
    name: "Mbah Dukun Usasama",
    view: `MATK +6%\nCSPD +12%\nKecepatan Aksi +3%\nMaxHP -25%\nAttack MP Recovery -50%`,
  },
  {
    code: 331,
    link: null,
    type: "WEAPON",
    name: "Potum Pahlawan",
    view: `MaxHP +10%\nPelindung Fraksional +10%\nAkurasi +10%\nAggro +10%`,
  },
  {
    code: 332,
    link: null,
    type: "WEAPON",
    name: "",
    view: ``,
  },
  {
    code: 333,
    link: null,
    type: "WEAPON",
    name: "Zahhak Machina",
    view: `Attack MP Recovery +5\nPelindung Fisik +1000\nMagical Barrier +1000`,
  },
  {
    code: 334,
    link: null,
    type: "WEAPON",
    name: "Komandan Golem",
    view: `ASPD +100\nPelindung Fisik +100\nTambahan Fisik +100%`,
  },
  {
    code: 335,
    link: null,
    type: "WEAPON",
    name: "Zolban",
    view: `Natural HP Regen -10%\nNatural MP Regen -10%\nATK +4%\nMATK +4%`,
  },
  {
    code: 336,
    link: null,
    type: "WEAPON",
    name: "Zega",
    view: `MaxHP +400\nKekebalan Sihir +2%\nKebal Air +1%\nAttack MP Recovery +3`,
  },
  {
    code: 337,
    link: null,
    type: "WEAPON",
    name: "Golem Pilar",
    view: `MaxMP +300\nPhysical Pierce +3%\nDaya Jarak Dekat +3%`,
  },
  {
    code: 338,
    link: null,
    type: "WEAPON",
    name: "",
    view: ``,
  },
  {
    code: 339,
    link: null,
    type: "WEAPON",
    name: "Nightmare Potum",
    view: `Aggro +10%\nPelindung Fraksional+2%\nMaxHP -5%`,
  },
  {
    code: 340,
    link: null,
    type: "WEAPON",
    name: "Potum Rembulan",
    view: `Attack MP Recovery +3\nCSPD -90%`,
  },
  {
    code: 341,
    link: null,
    type: "WEAPON",
    name: "Potum Ajaib",
    view: `MaxHP -10%\nEvasion Recharge +5%`,
  },
  {
    code: 342,
    link: null,
    type: "WEAPON",
    name: "Marchitar",
    view: `Stability +5%\nDodge +15%`,
  },
  {
    code: 343,
    link: null,
    type: "WEAPON",
    name: "Dukun Lapin",
    view: `CSPD +100\nPelindung Sihir +100\nTambahan Sihir +100%`,
  },
  {
    code: 344,
    link: null,
    type: "WEAPON",
    name: "",
    view: ``,
  },
  {
    code: 345,
    link: null,
    type: "WEAPON",
    name: "Imitacia",
    view: `MaxMP +200\nMATK +5%\nGuard Break +10%`,
  },
  {
    code: 346,
    link: null,
    type: "WEAPON",
    name: "Ganglef",
    view: `DEX +2%\nATK +3%\nASPD +1%`,
  },
  {
    code: 347,
    link: null,
    type: "WEAPON",
    name: "Golem Galian",
    view: `Guard Power +5%\nGuard Rate +5%`,
  },
  {
    code: 348,
    link: null,
    type: "WEAPON",
    name: "Pedang Sihir Iblis",
    view: `Critical Damage +5\nAggro +10%\nAttack MP Recovery +5`,
  },
  {
    code: 349,
    link: null,
    type: "WEAPON",
    name: "Gerbang Iblis",
    view: `DEX +2%\nMATK +3%\nCSPD +1%`,
  },
  {
    code: 350,
    link: null,
    type: "WEAPON",
    name: "",
    view: ``,
  },
  {
    code: 351,
    link: null,
    type: "WEAPON",
    name: "Colon Maut",
    view: `MaxMP -2000\nASPD +1000\nDaya Jarak Dekat +10%`,
  },
  {
    code: 352,
    link: null,
    type: "WEAPON",
    name: "Ksatria Buruk Dusta",
    view: `STR +3%\nATK +4%\nDEF -9%\nCritical +2%`,
  },
  {
    code: 353,
    link: null,
    type: "WEAPON",
    name: "Imitator",
    view: `ATK +5%\nAttack MP Recovery +2\nAntisipasi +10%`,
  },
  {
    code: 354,
    link: null,
    type: "WEAPON",
    name: "Iblis kristal Jahanam",
    view: `MATK+4%\nPeneterasi Sihir +3%\nAggro -5%`,
  },
  {
    code: 355,
    link: null,
    type: "ARMOR",
    name: "Altadar",
    view: `Stability +11%\nSTR +6%\nVIT +6%\nDengan Zirah Ringan:\nDaya Jarak Dekat +11%\nStability -5%\nDengan Zirah Berat:\nDaya Jarak Jauh +11%\nStability -5%`,
  },
  {
    code: 356,
    link: null,
    type: "ARMOR",
    name: "Auberkasa",
    view: `MaxHP +15%\nAggro +30%\nDEF +45`,
  },
  {
    code: 357,
    link: null,
    type: "ARMOR",
    name: "Sibylares",
    view: `ATK +5%\nMATK +5%\nPhysical Pierce +5%\nPeneterasi Sihir +5%\nCritical Rate +15\nMaxMP -100`,
  },
  {
    code: 358,
    link: null,
    type: "ARMOR",
    name: "Dr. Leonardo",
    view: `MATK +2%\nDaya Jarak Jauh +6%\nCritical Rate +10%\nMaxHP +5000\nResistansi Status Buruk +5%`,
  },
  {
    code: 359,
    link: null,
    type: "ARMOR",
    name: "",
    view: ``,
  },
  {
    code: 360,
    link: null,
    type: "ARMOR",
    name: "DX Fighter",
    view: `ATK +2%\nDaya Jarak Dekat +6%\nAkurasi +10%\nMaxHP +5000\nPelindung Fraksional +5%`,
  },
  {
    code: 361,
    link: null,
    type: "ARMOR",
    name: "Kruztor",
    view: `MaxHP +5%\nDodge +5%\nKekebalan Fisik +5%\nKekebalan Sihir +5%\nKebal Normal +5%`,
  },
  {
    code: 362,
    link: null,
    type: "ARMOR",
    name: "Doktor Pom Pom",
    view: `Daya Jarak Dekat +7%\nCritical Rate +7%\nResistensi Status Buruk +7%`,
  },
  {
    code: 363,
    link: null,
    type: "ARMOR",
    name: "Orang2an Sawah Maut",
    view: `Daya Jarak Jauh +6%\nAggro -15%\nMaxHP -30%`,
  },
  {
    code: 364,
    link: null,
    type: "ARMOR",
    name: "Arachnidemon",
    view: `ATK +8%\nCritical Rate +8\nMaxHP -400\nMaxMP -400\nDengan Perisai:\nDaya Jarak Dekat +4%`,
  },
  {
    code: 365,
    link: null,
    type: "ARMOR",
    name: "",
    view: ``,
  },
  {
    code: 366,
    link: null,
    type: "ARMOR",
    name: "Phantom Wisp",
    view: `Akurasi +20%\nCritical Rate +10\nEvasion Recharge +10%\nDodge Absolut +5%`,
  },
  {
    code: 367,
    link: null,
    type: "ARMOR",
    name: "Gopherga",
    view: `MaxHP +3000\nKekebalan Fisik +3%\nKekebalan Sihir +3%\nDaya Jarak Dekat +6%\nAggro +15%`,
  },
  {
    code: 368,
    link: null,
    type: "ARMOR",
    name: "Quasar Jahanam",
    view: `MaxMP +1000\nCSPD +300\nKecepatan Aksi +1%`,
  },
  {
    code: 369,
    link: null,
    type: "ARMOR",
    name: "Nemopirania",
    view: `Attack MP Recovery +10\nKecepatan Pelindung +10%\nKebal Air +10%`,
  },
  {
    code: 370,
    link: null,
    type: "ARMOR",
    name: "Sosok Jahat",
    view: `MaxHP +1500\nMaxMP +300\nMATK +6%\nEvasion Recharge -10%`,
  },
  {
    code: 371,
    link: null,
    type: "ARMOR",
    name: "",
    view: ``,
  },
  {
    code: 372,
    link: null,
    type: "ARMOR",
    name: "Pilz Erosi",
    view: `MaxHP +30%\nKekebalan Fisik -10%\nKekebalan Sihir -10%`,
  },
  {
    code: 373,
    link: null,
    type: "ARMOR",
    name: "Golem Preman",
    view: `Pelindung Fraksional 10%\nCSPD +15%\nAggro -20%`,
  },
  {
    code: 374,
    link: null,
    type: "ARMOR",
    name: "Permaisuri Besi",
    view: `MaxHP +20%\nKekebalan Fisik +10%\nMATK +5%\nPeneterasi Sihir +10%\nCSPD +20%\nMaxMP -300`,
  },
  {
    code: 375,
    link: null,
    type: "ARMOR",
    name: "Noeliel",
    view: `MATK +5%\nCSPD +3%\nAttack MP Recovery +1%`,
  },
  {
    code: 376,
    link: null,
    type: "ARMOR",
    name: "Gagak Penyihir Hebat",
    view: `Stability +4%\nKecepatan aksi +2%\nAkurasi Absolut +1%\nResistensi Status Buruk -14%`,
  },
  {
    code: 377,
    link: null,
    type: "ARMOR",
    name: "",
    view: ``,
  },
  {
    code: 378,
    link: null,
    type: "ARMOR",
    name: "Goldoon",
    view: `ATK +3%\nMATK +3%\nAkurasi +3%\nAggro -3%`,
  },
  {
    code: 379,
    link: null,
    type: "ARMOR",
    name: "Usakichi",
    view: `MaxMP +100 ATK +1%\nSerangan Menghunus +1%\nKebal Normal -1%`,
  },
  {
    code: 380,
    link: null,
    type: "ARMOR",
    name: "Pedang Maton",
    view: `STR +3%\nDaya Jarak Jauh +4%\nAkurasi +5%\nMaxHP -1000`,
  },
  {
    code: 381,
    link: null,
    type: "ARMOR",
    name: "Tortuga",
    view: `MaxHP +1%\nKekebalan Fisik +3%\nGuard Recharge +5%`,
  },
  {
    code: 382,
    link: null,
    type: "ARMOR",
    name: "Elang Zamrud",
    view: `MaxMP +300\nCSPD +100\nAttack MP Recovery +1`,
  },
  {
    code: 383,
    link: null,
    type: "ARMOR",
    name: "",
    view: ``,
  },
  {
    code: 384,
    link: null,
    type: "ARMOR",
    name: "Ifrid",
    view: `MaxMP +600\nPelindung Fraksional +12%`,
  },
  {
    code: 385,
    link: null,
    type: "ARMOR",
    name: "Forestia",
    view: `MATK +1%\nKekebalan Sihir +3%\nEvasion Recharge +5%`,
  },
  {
    code: 386,
    link: null,
    type: "ARMOR",
    name: "Colon Komandan",
    view: `MaxHP +150\nMaxMP +50`,
  },
  {
    code: 387,
    link: null,
    type: "ARMOR",
    name: "Cerberus",
    view: `Physical Pierce +3%\nCritical Damage +3\nSerangan Menghunus +3%`,
  },
  {
    code: 388,
    link: null,
    type: "ARMOR",
    name: "Cerabes",
    view: `MaxHP +1000\nCritical Damage +1`,
  },
  {
    code: 389,
    link: null,
    type: "ARMOR",
    name: "",
    view: ``,
  },
  {
    code: 390,
    link: null,
    type: "ARMOR",
    name: "Boss Roga",
    view: `MaxHP +1000\nWeapon ATK +1%`,
  },
  {
    code: 391,
    link: null,
    type: "ARMOR",
    name: "Arcoiris",
    view: `Natural HP Regen +10%\nMaxHP +10%\nDEF +10%`,
  },
  {
    code: 392,
    link: null,
    type: "SPECIAL",
    name: "Naga Terong Auvio",
    view: `MaxMP +300\nDaya Jarak Dekat +4%\nASPD +500\nDaya Jarak Jauh -12%\nDengan Kitab Ninjutsu:\nSerangan Menghunus +5%\nCritical Rate +5`,
  },
  {
    code: 393,
    link: null,
    type: "SPECIAL",
    name: "Vodre",
    view: `Antisipasi +5%\nKekebalan Fisik +5%\nKekebalan Sihir +5%\nCritical Damage -150`,
  },
  {
    code: 394,
    link: null,
    type: "SPECIAL",
    name: "Syaman Hitam Hutan Hantu",
    view: `Peneterasi Sihir +5%\nCSPD +20%\nEvasion Recharge +10%\nMaxMP -300\nDengan Perisai:\nStability +5%\nATK -10%`,
  },
  {
    code: 395,
    link: null,
    type: "SPECIAL",
    name: "Goblin Makelar",
    view: `MaxMP +300\nDaya Jarak Jauh +3%\nDEX +3%\nDengan Panah:\nDaya Jarak Jauh +5%\nDengan Belati:\nTambahan Fisik +50%\nDengan Perisai:\nAggro +25%`,
  },
  {
    code: 396,
    link: null,
    type: "SPECIAL",
    name: "",
    view: ``,
  },
  {
    code: 397,
    link: null,
    type: "SPECIAL",
    name: "Kapten Sihir & si B",
    view: `Daya Jarak Dekat +3%\nSerangan Menghunus +3%\nMaxMP -150\nKebal Api +10%\nKebal Air +10%\nKebal Angin +10%\nKebal Bumi +15%`,
  },
  {
    code: 398,
    link: null,
    type: "SPECIAL",
    name: "Stellar Ooze II",
    view: `ATK +5%\nSerangan Menghunus +5%\nPhysical Pierce +5%\nMaxMP +150\nNatural MP Regen +15%\nReduksi DMG (Bowling) +15%\nRevive Time +60%`,
  },
  {
    code: 399,
    link: null,
    type: "SPECIAL",
    name: "Trus",
    view: `Guard Break +10%\nPhysical Pierce +10%\nDengan Pedang Ganda :\nGuard Recharge +25%\nGuard Power +25%`,
  },
  {
    code: 400,
    link: null,
    type: "SPECIAL",
    name: "Wolkissa",
    view: `Attack MP Recovery +5\nVIT +5%\nResistensi Status Buruk +5%\nDengan Perisai:\nAggro +15%`,
  },
  {
    code: 401,
    link: null,
    type: "SPECIAL",
    name: "Ignitrus",
    view: `MaxHP +1000\nMaxMP +100\nKebal Api +20%\n+5% stronger against Fire`,
  },
  {
    code: 402,
    link: null,
    type: "SPECIAL",
    name: "",
    view: ``,
  },
  {
    code: 403,
    link: null,
    type: "SPECIAL",
    name: "Ruzart",
    view: `Dodge +10\nCritical Rate +10`,
  },
  {
    code: 404,
    link: null,
    type: "SPECIAL",
    name: "Kapten Amiya",
    view: `MaxHP +1000\nMaxMP +100\nAttack MP Recovery +10`,
  },
  {
    code: 405,
    link: null,
    type: "SPECIAL",
    name: "Penyihir Bintang",
    view: `MATK +9%\nCSPD +9%\nAntisipasi +9%\nDengan Tongkat:\nAggro -9%\nDengan Perisai:\nAggro +9%`,
  },
  {
    code: 406,
    link: null,
    type: "SPECIAL",
    name: "Penyihir Naga",
    view: `Critical Damage +5%\nAttack MP Recovery -100%`,
  },
  {
    code: 407,
    link: null,
    type: "SPECIAL",
    name: "Potumotter",
    view: `MaxMP +400\nAggro -30%\nKebal Normal +20%`,
  },
  {
    code: 408,
    link: null,
    type: "SPECIAL",
    name: "",
    view: ``,
  },
  {
    code: 409,
    link: null,
    type: "SPECIAL",
    name: "Volgagon",
    view: `Critical Rate +20%\nASPD +1000\nCSPD -80%`,
  },
  {
    code: 410,
    link: null,
    type: "SPECIAL",
    name: "Violangkara",
    view: `Tambahan Fisik +50%\nATK +1%\nASPD +250`,
  },
  {
    code: 411,
    link: null,
    type: "SPECIAL",
    name: "Grimuckus",
    view: `Tambahan Sihir +50%\nMATK +1%\nASPD +250`,
  },
  {
    code: 412,
    link: null,
    type: "SPECIAL",
    name: "Puaka Maut",
    view: `Serangan Menghunus +10%\nAkurasi +15%\nAggro -20%`,
  },
  {
    code: 413,
    link: null,
    type: "SPECIAL",
    name: "Seele Zauga",
    view: `Critical Rate +15\nKekebalan Fisik +5%\nKekebalan Sihir +5%\nKecepatan Item -1.0s`,
  },
  {
    code: 414,
    link: null,
    type: "SPECIAL",
    name: "",
    view: ``,
  },
  {
    code: 415,
    link: null,
    type: "SPECIAL",
    name: "Felien",
    view: `MaxMP +300\nAkurasi +20\nAkurasi +10%\nAkurasi Absolut +5%`,
  },
  {
    code: 416,
    link: null,
    type: "SPECIAL",
    name: "Crystal Titan",
    view: `MaxHP +1000\nMaxHP +10%\nPelindung Fraksional 10%`,
  },
  {
    code: 417,
    link: null,
    type: "SPECIAL",
    name: "Choiyaki Mentai",
    view: `MaxMP +300\nDaya Jarak Dekat +2%\nKebal Api +1%\nMATK -10%\nReduksi DMG (Lantai) -20%`,
  },
  {
    code: 418,
    link: null,
    type: "SPECIAL",
    name: "Venena",
    view: `MaxMP +500\nATK +1%\nMATK +1%\nStability +2%`,
  },
  {
    code: 419,
    link: null,
    type: "SPECIAL",
    name: "Viscum",
    view: `MaxHP +100\nAttack MP Recovery +3`,
  },
  {
    code: 420,
    link: null,
    type: "SPECIAL",
    name: "",
    view: ``,
  },
  {
    code: 421,
    link: null,
    type: "SPECIAL",
    name: "Violacoon",
    view: `MATK -6%\nEvasion Recharge +4%\nAggro +8%`,
  },
  {
    code: 422,
    link: null,
    type: "SPECIAL",
    name: "Tentara Batu",
    view: `ATK -6%\nGuard Recharge +4%\nAggro +8%`,
  },
  {
    code: 423,
    link: null,
    type: "SPECIAL",
    name: "Baron Bling-bling",
    view: `ATK +1%\nMATK +1%\nCritical Damage +1%\nAttack MP Recovery +3`,
  },
  {
    code: 424,
    link: null,
    type: "SPECIAL",
    name: "Ooze",
    view: `ATK +2%\nMATK +2%\nDEF -2%\nMDEF -2%`,
  },
  {
    code: 425,
    link: null,
    type: "SPECIAL",
    name: "Nini",
    view: `MATK +100\nCSPD -1000`,
  },
  {
    code: 426,
    link: null,
    type: "SPECIAL",
    name: "",
    view: ``,
  },
  {
    code: 427,
    link: null,
    type: "SPECIAL",
    name: "Goovua",
    view: `Serangan Menghunus +100\nEvasion Recharge +6%\nAGI +3%`,
  },
  {
    code: 428,
    link: null,
    type: "SPECIAL",
    name: "Potum Emas",
    view: `Untradable
    Base Drop Rate +1%`,
  },
  {
    code: 429,
    link: null,
    type: "SPECIAL",
    name: "Kristal Jahat",
    view: `Attack MP Recovery +5`,
  },
  {
    code: 430,
    link: null,
    type: "SPECIAL",
    name: "Don Yeti",
    view: `ATK +100\nASPD -1000`,
  },
  {
    code: 431,
    link: null,
    type: "SPECIAL",
    name: "Dark Mushroom",
    view: `ATK +1%\nMATK +1%\nKecepatan Aksi +1%`,
  },
  {
    code: 432,
    link: null,
    type: "SPECIAL",
    name: "",
    view: ``,
  },
  {
    code: 433,
    link: null,
    type: "SPECIAL",
    name: "Bexiz",
    view: `MaxMP -100\nAkurasi +15%\nCritical Rate +5\nWeapon ATK +10%`,
  },
  {
    code: 434,
    link: null,
    type: "SPECIAL",
    name: "Titeres",
    view: `Attack MP Recovery +10\nDodge +20\nDodge +10%\nDodge Absolut +5%`,
  },
  {
    code: 435,
    link: null,
    type: "ADDITIONAL",
    name: "Falburrows",
    view: `Daya Jarak Jauh +9%\nMaxMP +200\nDodge +10%\nDodge Absolut +5%\nDengan Bowgun:\nDaya Jarak Dekat +9%`,
  },
  {
    code: 436,
    link: null,
    type: "ADDITIONAL",
    name: "Magi Filecia",
    view: `MATK +9%\nINT +3%\nStability +6%\nDengan Tongkat:\nGuard Break +10%\nDengan Pesawat Sihir:\nReduksi DMG (Bowling) +20%`,
  },
  {
    code: 437,
    link: null,
    type: "ADDITIONAL",
    name: "Lunadore",
    view: `Base Drop Rate +1%`,
  },
  {
    code: 438,
    link: null,
    type: "ADDITIONAL",
    name: "Purro",
    view: `Base Drop Rate +1%`,
  },
  {
    code: 439,
    link: null,
    type: "ADDITIONAL",
    name: "",
    view: ``,
  },
  {
    code: 440,
    link: null,
    type: "ADDITIONAL",
    name: "Perro",
    view: `Base Drop Rate +1%`,
  },
  {
    code: 441,
    link: null,
    type: "ADDITIONAL",
    name: "Mieli",
    view: `Peneterasi Sihir +10%\nCritical Rate +20%\nASPD +400\nCSPD +400\nMaxHP -20%`,
  },
  {
    code: 442,
    link: null,
    type: "ADDITIONAL",
    name: "Lefina Jahat",
    view: `ATK +8%\nPhysical Pierce +10%\nCritical Rate +12\nMATK -4%\nKekebalan Fisik -20%\nDengan Zirah Berat:\nKekebalan Fisik +24%`,
  },
  {
    code: 443,
    link: null,
    type: "ADDITIONAL",
    name: "Eidenliebe",
    view: `MaxHP +12%\nPeneterasi Sihir +10%\nAggro -15%`,
  },
  {
    code: 444,
    link: null,
    type: "ADDITIONAL",
    name: "Naga Junior Zyvio",
    view: `ATK +5%\nCritical Rate +15\nMaxMP +100\nGuard Break 5%`,
  },
  {
    code: 445,
    link: null,
    type: "ADDITIONAL",
    name: "",
    view: ``,
  },
  {
    code: 446,
    link: null,
    type: "ADDITIONAL",
    name: "Raja Kerbau",
    view: `Aggro -20%`,
  },
  {
    code: 447,
    link: null,
    type: "ADDITIONAL",
    name: "Bonivio",
    view: `Base Drop Rate +1%`,
  },
  {
    code: 448,
    link: null,
    type: "ADDITIONAL",
    name: "Datuk Nezim",
    view: `MaxHP +3000\nVIT +2%\nCritical Rate +10\nDengan Sarung Tinju:\n Daya Jarak Dekat +3%`,
  },
  {
    code: 449,
    link: null,
    type: "ADDITIONAL",
    name: "Adaro",
    view: `MATK +6%\nCritical Damage +6\nMaxHP +1000\nDengan Zirah Berat:\nAggro +10%`,
  },
  {
    code: 450,
    link: null,
    type: "ADDITIONAL",
    name: "Mercy",
    view: `Critical Rate +15\nAggro -15%`,
  },
  {
    code: 451,
    link: null,
    type: "ADDITIONAL",
    name: "",
    view: ``,
  },
  {
    code: 452,
    link: null,
    type: "ADDITIONAL",
    name: "Omochi",
    view: `Base Drop Rate +1%`,
  },
  {
    code: 453,
    link: null,
    type: "ADDITIONAL",
    name: "Ayah Yashiro Azuki",
    view: `ATK +4%\nDaya Jarak Dekat +3%\nASPD +20%\nAggro -10%`,
  },
  {
    code: 454,
    link: null,
    type: "ADDITIONAL",
    name: "Narumi Hina",
    view: `MATK +4%\nDaya Jarak Jauh +3%\nCSPD +20%\nAggro -10%`,
  },
  {
    code: 455,
    link: null,
    type: "ADDITIONAL",
    name: "Goldenia",
    view: `MaxHP +2000\nPelindung Fraksional 10%\nMaxMP -300`,
  },
  {
    code: 456,
    link: null,
    type: "ADDITIONAL",
    name: "Biskuit Buatan Tangan",
    view: `Physical Pierce +10%\nMaxHP +12%\nAggro -15%`,
  },
  {
    code: 457,
    link: null,
    type: "ADDITIONAL",
    name: "",
    view: ``,
  },
  {
    code: 458,
    link: null,
    type: "ADDITIONAL",
    name: "Celeng Mini Merah Putih",
    view: `Base Drop Rate +1%`,
  },
  {
    code: 459,
    link: null,
    type: "ADDITIONAL",
    name: "Altoblepas",
    view: `Critical Damage +4\nDEX +1%\nAkurasi -20%`,
  },
  {
    code: 460,
    link: null,
    type: "ADDITIONAL",
    name: "Iconos Emas",
    view: `MaxHP +1000\nReduksi DMG (Terjang) +10%`,
  },
  {
    code: 461,
    link: null,
    type: "ADDITIONAL",
    name: "Gespenst II",
    view: `Critical Rate +10\nAkurasi +30\nMaxMP +200\nCSPD +200`,
  },
  {
    code: 462,
    link: null,
    type: "ADDITIONAL",
    name: "Ibu Yashiro Azuki",
    view: `Critical Rate +10\nKekebalan Fisik +5%\nKekebalan Sihir +5%\nReduksi DMG (Peluru) +10%`,
  },
  {
    code: 463,
    link: null,
    type: "ADDITIONAL",
    name: "",
    view: ``,
  },
  {
    code: 464,
    link: null,
    type: "ADDITIONAL",
    name: "Warmonger",
    view: `Critical Rate +6\nCritical Damage +2`,
  },
  {
    code: 465,
    link: null,
    type: "ADDITIONAL",
    name: "Naga Senja",
    view: `Daya Jarak Dekat +4%\nDaya Jarak Jauh +4%\nSerangan Menghunus +4%`,
  },
  {
    code: 466,
    link: null,
    type: "ADDITIONAL",
    name: "Potum Surya",
    view: `ASPD +300\nCSPD +300\nMaxHP -5%\nMaxMP -75`,
  },
  {
    code: 467,
    link: null,
    type: "ADDITIONAL",
    name: "Seltirios",
    view: `MaxMP -150\nCSPD +300`,
  },
  {
    code: 468,
    link: null,
    type: "ADDITIONAL",
    name: "Pumpking",
    view: `Critical Damage +1\nKebal Api +2%\nAttack MP Recovery +3`,
  },
  {
    code: 469,
    link: null,
    type: "ADDITIONAL",
    name: "",
    view: ``,
  },
  {
    code: 470,
    link: null,
    type: "ADDITIONAL",
    name: "Grylle",
    view: `MaxHP +500\nDEF +5%\nGuard Power +5%`,
  },
  {
    code: 471,
    link: null,
    type: "ADDITIONAL",
    name: "Naga Sabana Yelb",
    view: `ATK +3%\nASPD +50%\nDaya Jarak Jauh -10%`,
  },
  {
    code: 472,
    link: null,
    type: "ADDITIONAL",
    name: "Grand Pojo",
    view: `Base Drop Rate +1%`,
  },
  {
    code: 473,
    link: null,
    type: "ADDITIONAL",
    name: "Tengkorak Emas",
    view: `MaxHP -10%\nASPD +300`,
  },
  {
    code: 474,
    link: null,
    type: "ADDITIONAL",
    name: "Celeng Raksasa",
    view: `MaxHP +50\nMaxMP +50\nDaya Jarak Dekat +1%`,
  },
  {
    code: 475,
    link: null,
    type: "ADDITIONAL",
    name: "",
    view: ``,
  },
  {
    code: 476,
    link: null,
    type: "ADDITIONAL",
    name: "Dusk Machina",
    view: `MaxHP +20%\nAggro +10%\nDaya Jarak Jauh -10%`,
  },
  {
    code: 477,
    link: null,
    type: "ADDITIONAL",
    name: "Kapten Karatan",
    view: `DEF +100 MDEF +100\nPelindung Fisik +500\nPelindung Sihir +500`,
  },
  {
    code: 478,
    link: null,
    type: "ADDITIONAL",
    name: "Chocolate Ooze",
    view: `CSPD +500\nMaxHP -10%\nMaxMP +200`,
  },
  {
    code: 479,
    link: null,
    type: "ADDITIONAL",
    name: "Candela",
    view: `MaxHP +10%\nMaxMP -200\nASPD +500`,
  },
  {
    code: 480,
    link: null,
    type: "ADDITIONAL",
    name: "Ratu Kuno",
    view: `MATK +3%\nCSPD +50%\nDaya Jarak Dekat -10%`,
  },
  {
    code: 481,
    link: null,
    type: "NORMAL",
    name: "Lobalawar",
    view: `Stability 4%\nAkurasi 4%\nCritical Rate 4%`,
  },
  {
    code: 482,
    link: 323,
    type: "UPGRADE",
    name: "Diark",
    view: `MATK +8%\nPeneterasi Sihir +20%\nKecepatan Merapal -16%`,
  },
  {
    code: 483,
    link: 234,
    type: "UPGRADE",
    name: "Gegner",
    view: `MATK +10%\nINT +6%\nKecepatan Merapal +40%\nAttack MP Recovery +10%`,
  },
  {
    code: 484,
    link: null,
    type: "SPECIAL",
    name: "Bayangan Jeritan",
    view: `MaxMP +300\nCritical Rate +20%\nKecepatan Merapal +1000\nDEF -40%`,
  },
  {
    code: 485,
    link: 26,
    type: "UPGRADE",
    name: "Gerumi Kuat",
    view: `MaxHP +400\nMaxMP +200\nStability +2%\nAccuracy +2%\nCritical Rate +4`,
  },
  {
    code: 486,
    link: null,
    type: "SPECIAL",
    name: "Pelulu Raksasa",
    view: `Daya Jarak Dekat +10%\nMaxHP +30%%\nCritical Rate +50%\nMaxMP -100\nDengan Zirah Ringan:\nPeneterasi Fisik -10%`,
  },
  {
    code: 487,
    link: null,
    type: "ARMOR",
    name: "Bangrudom",
    view: `ATK +10%\nMATK +10%\nKecepatan Serangan +10%\nKecepatan Merapal +10%\nMaxHP -20%\nDengan Perisai\nDex +5%\nDengan ZIrah Ringan\nPeneterasi SIhir +5%`,
  },
  {
    code: 488,
    link: 285,
    type: "UPGRADE",
    name: "limacina",
    view: `Resistensi Status Buruk +5%\nKekebalan Fisik +5%\nKekebalan Sihir +5%`,
  },
  {
    code: 489,
    link: 221,
    type: "UPGRADE",
    name: "Vatudo",
    view: `MATK +10%\nPeneterasi Sihir +7%\nAggro -11%\nMDEF -30%`,
  },
  {
    code: 490,
    link: 459,
    type: "UPGRADE",
    name: "Jiva",
    view: `MATK +8%\nCritical Damage +6\nDex +3%\nAccuracy -20%`,
  },
  {
    code: 491,
    link: 215,
    type: "UPGRADE",
    name: "Naga Meraung Bovinari",
    view: `Daya Jarak Dekat +7%\nAttack MP Recovery +15\nPelindung Fisik +3000\nPelindung Sihir +3000`,
  },
  {
    code: 492,
    link: 316,
    type: "UPGRADE",
    name: "Doridodi",
    view: `Daya Jarak Jauh +10%\nAccuracy +17%\nMaxHP -25%`,
  },
  {
    code: 493,
    link: 240,
    type: "UPGRADE",
    name: "Humida",
    view: `MaxMP +700\nATK +4%\nMATK +4%\nStability +4%`,
  },
  {
    code: 494,
    link: 231,
    type: "UPGRADE",
    name: "Torexesa",
    view: `ATK +10%\nMATK +10%\nAttack MP Recovery +4\nMaxMP -200`,
  },
  {
    code: 495,
    link: 172,
    type: "UPGRADE",
    name: "Breeta",
    view: `Attack MP Recovery +15%\nMaxHP +5000%\nStability +2%`,
  },
  {
    code: 496,
    link: null,
    type: "NORMAL",
    name: "VIT+8",
    view: `VIT +8`,
  },
  {
    code: 497,
    link: 216,
    type: "UPGRADE",
    name: "Meteora",
    view: `Serangan Menghunus +9%\nPeneterasi Fisik +5%\nCritical Damage +7`,
  },
  {
    code: 498,
    link: null,
    type: "ARMOR",
    name: "Tangan Mulgoon",
    view: `Daya Jarak Dekat +6%\nDaya Jarak Jauh +4%\nAccuracy +5%\nMaxHP +10000\nMaxMP -100`,
  },
  {
    code: 499,
    link: null,
    type: "ADDITIONAL",
    name: "Jibril",
    view: `Daya Jarak Dekat +3%\nDaya Jarak Jauh +5%\nMaxMP +100\nCritical Rate +8\nAntisipasi +1%\nNatural MP Regen +2\nNatural MP Regen +4%`,
  },
  {
    code: 500,
    link: 499,
    type: "UPGRADE",
    name: "Jibril II",
    view: `Daya Jarak Dekat +6%\nDaya Jarak Jauh +8%\nMaxMP +100\nCritical Rate +12\nAntisipasi +2%\nNatural MP Regen +4\nNatural MP Regen +8%`,
  },
  {
    code: 501,
    link: 500,
    type: "UPGRADE",
    name: "Jibril III",
    view: `Daya Jarak Dekat +9%\nDaya Jarak Jauh +11%\nMaxMP +100\nCritical Rate +16\nAntisipasi +3%\nNatural MP Regen +6\nNatural MP Regen +12%`,
  },
  {
    code: 502,
    link: 407,
    type: "UPGRADE",
    name: "Potumotter II",
    view: `MaxMP +400\nnKecepatan Aksi +1%\nAggro -30%\nKebal Normal +25%`,
  },
  {
    code: 503,
    link: 180,
    type: "UPGRADE",
    name: "Potum Pahlawan IV",
    view: `MaxHP +13%\nPelindung Fraksional +16%\nAkurasi +19%\nAggro +22%`,
  },
  {
    code: 504,
    link: 198,
    type: "UPGRADE",
    name: "Deformis",
    view: `ATK +11%\nAttack MP Recovery +8\nAntisipasi 14%\nMaxMP -200`,
  },
  {
    code: 505,
    link: 239,
    type: "UPGRADE",
    name: "Wiltileaf",
    view: `ATK +9%\nCritical Damage +12\nKecepatan Aksi 0%\nKekebalan Sihir -15%`,
  },
  {
    code: 506,
    link: 410,
    type: "UPGRADE",
    name: "Violangkara G",
    view: `Tambahan Fisik 75%\nTambahan Sihir 75%\nDengan Pedang 1T\nTambahan Fisik 25%\nDengan Pesawat Sihir\n Tambahan Sihir 25%`,
  },
  {
    code: 507,
    link: 131,
    type: "UPGRADE",
    name: "Kijimu Agung",
    view: `MaxHP +700\nMaxMP +300\nPeneterasi Fisik +1%\nPeneterasi Sihir +1%`,
  },
  {
    code: 508,
    link: 215,
    type: "UPGRADE",
    name: "Ratu Rosemee",
    view: `Daya Jarak Jauh +5%\nAttack MP Recovery +5\nPeneterasi Sihir +5%\nCritical Rate +5%`,
  },
  {
    code: 509,
    link: 372,
    type: "UPGRADE",
    name: "Tulin Max",
    view: `MaxHP -30%\nKekebalan Fisik +10%\nKekebalan Sihir +10%\nCritical Rate +10`,
  },
  {
    code: 510,
    link: null,
    type: "SPECIAL",
    name: "Zeagrystal",
    view: `Daya Jarak Dekat +2%\nStability +2%\nKekebalan Fisik +3%\nkekebalan Sihir +3%\nMaxMP -100\nDengan perisai:\nResistensi Status Buruk +5%`,
  },
  {
    code: 511,
    link: 510,
    type: "UPGRADE",
    name: "Monster Kristal Abisal",
    view: `Daya Jarak Dekat +4%\nStability +4%\nKekebalan Fisik +6%\nkekebalan Sihir +6%\nMaxMP -200\nDengan perisai:\nResistensi Status Buruk +5%`,
  },
  {
    code: 512,
    link: null,
    type: "ADDITIONAL",
    name: "Castilia",
    view: `Daya Jarak Dekat +12%\nDaya Jarak Jauh +6%\nAkurasi +10%\nDengan Peralatan Sihir:\nMotion Speed +5%\nDengan Ninjutsu Scroll:\nPenetrasi Sihir +10%`
  },
  {
    code: 513,
    link: 317,
    type: "UPGRADE",
    name: "Fubbit",
    view:  `ATK +6%\nPenetrasi Fisik +20%\nAggro -15%\nResistensi Status Buruk -15%\nMax MP -200`
  },
  {
    code: 514,
    link: 288,
    type: "UPGRADE",
    name: "Dondolion",
    view: `MaxMP +500\nAttack MP Recovery +4\nKecepatan Merapal+300\nDengan Zirah Ringan:\nStability +6%`
  },
  {
    cod: 515,
    link: 357,
    type: "UPGRADE",
    name: "Bemoz",
    view: `MaxMP -150\nATK +6%\nMATK +6%\nPenetrasi Fisik +8%\nPenetrasi Sihir +8%\n Critical Rate +17`
  },
  {
    code: 516,
    link: 321,
    type: "Upgrade",
    name: "Sakura Musim Panas",
    view: `MATK +11%\nCritical Rate +13\n Aggro -15%`
  },
  {
    code: 517,
    link: 203,
    type: "Upgrade",
    name: "Shawle Terlarang",
    view: `MaxMP -200\nDaya Jarak Dekat +10%\nDaya Jarak Jauh +10%\nSerangan Menghunus +10%`
  },
  {
    code: 518,
    link: 317,
    type: "Upgrade",
    name: "Dango Sakura ",
    view: `ATK +4%\nPenetrasi Fisik +20%\nAggro -10%\nResistansi Status Buruk -5%\nMaxMP -100`,
  },
  {
    code: 519,
    link: null,
    type: "Normal",
    name: "Jejak Bayangan nan Jauh",
    view: `Penetrasi Fisik +5%\nASPD -250\nDaya Jarak Dekat +10%`
  }
]
